# Generated by Django 6.0.1 on 2026-01-14 21:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('action_type', models.CharField(choices=[('webhook', 'Webhook'), ('email', 'Email Notification'), ('celery_task', 'Celery Task'), ('log', 'Log Message')], max_length=50)),
                ('config', models.JSONField(default=dict, help_text='Action-specific configuration (webhook URL, email template, task name, etc.)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which actions are executed (lower = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['trigger', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('read', 'Read'), ('any', 'Any')], default='any', help_text='The action type to trigger on', max_length=50)),
                ('reference_role', models.CharField(blank=True, help_text="When matching references, only match this role (e.g., 'affected', 'created', 'parent'). Leave blank to match any role.", max_length=50)),
                ('source_filter', models.CharField(blank=True, help_text='Only trigger for specific sources (api, management_command, etc.)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('result', models.JSONField(blank=True, default=dict, help_text='Execution result or error details')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='actions.action')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
