# Generated by Django 6.0.1 on 2026-01-14 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0001_initial'),
        ('audit_log', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('organizations', '0003_organization_unique_organization_name'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionexecution',
            name='audit_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_executions', to='audit_log.auditlogentry'),
        ),
        migrations.AddField(
            model_name='trigger',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Limit trigger to specific organization (null = global)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='trigger',
            name='target_content_type',
            field=models.ForeignKey(help_text='The model type to trigger on (e.g., Organization, Workspace)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='trigger',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='Limit trigger to specific workspace', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='action',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='actions.trigger'),
        ),
    ]
