# Generated by Django 6.0.1 on 2026-01-14 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_manager', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacegroupmember',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_workspace_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='role',
            field=models.ForeignKey(limit_choices_to={'scope': 'workspace'}, on_delete=django.db.models.deletion.PROTECT, related_name='workspace_user_members', to='users_manager.role'),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_members', to='workspaces.workspace'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='unique_group_user'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('name', 'scope'), name='unique_role_name_per_scope'),
        ),
        migrations.AddConstraint(
            model_name='organizationmember',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='unique_org_user_member'),
        ),
        migrations.AddConstraint(
            model_name='organizationgroupmember',
            constraint=models.UniqueConstraint(fields=('organization', 'group'), name='unique_org_group_member'),
        ),
        migrations.AddConstraint(
            model_name='workspacegroupmember',
            constraint=models.UniqueConstraint(fields=('workspace', 'group'), name='unique_workspace_group_member'),
        ),
        migrations.AddConstraint(
            model_name='workspacemember',
            constraint=models.UniqueConstraint(fields=('workspace', 'user'), name='unique_workspace_user_member'),
        ),
    ]
