# Generated by Django 6.0.1 on 2026-01-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_manager', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lock_expiration',
            field=models.DateTimeField(blank=True, help_text='Account is locked until this time due to failed login attempts', null=True),
        ),
    ]
