# Generated by Django 6.0.1 on 2026-01-19 01:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_manager', '0003_user_lock_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='scope',
            field=models.CharField(choices=[('instance', 'Instance'), ('organization', 'Organization'), ('workspace', 'Workspace')], help_text='Where this role can be applied', max_length=20),
        ),
        migrations.CreateModel(
            name='InstanceGroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_instance_group_roles', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_roles', to='users_manager.group')),
                ('role', models.ForeignKey(limit_choices_to={'scope': 'instance'}, on_delete=django.db.models.deletion.PROTECT, related_name='instance_group_members', to='users_manager.role')),
            ],
            options={
                'ordering': ['-granted_at'],
                'constraints': [models.UniqueConstraint(fields=('group', 'role'), name='unique_instance_group_role')],
            },
        ),
        migrations.CreateModel(
            name='InstanceMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_instance_roles', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(limit_choices_to={'scope': 'instance'}, on_delete=django.db.models.deletion.PROTECT, related_name='instance_members', to='users_manager.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-granted_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'role'), name='unique_instance_user_role')],
            },
        ),
    ]
