"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-p*s+c^7)m$n61it(mj1j@j&*j9i+kad*s3p)u2_(!7kqq0x-yx"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    "rest_framework",
    "rest_framework_gis",
    "drf_spectacular",
    "django_filters",
    "polymorphic",
    "silk",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "core",
    "organizations",
    "workspaces",
    "todos",
    "assets",
    "files_manager",
    "pgtrigger",
    "utils",
    "users_manager",
    "audit_log",
    "actions",
    "auth_manager",
]

# Custom User Model
AUTH_USER_MODEL = "users_manager.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "silk.middleware.SilkyMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "audit_log.middleware.AuditLogMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "app.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import os

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": os.environ.get("DJANGO_DB_NAME", "mydb"),
        "USER": os.environ.get("DJANGO_DB_USER", "myuser"),
        "PASSWORD": os.environ.get("DJANGO_DB_PASSWORD", "mypassword"),
        "HOST": os.environ.get("DJANGO_DB_HOST", "localhost"),
        "PORT": os.environ.get("DJANGO_DB_PORT", "5432"),
    }
}

# Cache configuration - using Redis
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": f"redis://{os.environ.get('REDIS_HOST', 'redis')}:6379/1",
        "TIMEOUT": 300,  # Default cache TTL: 5 minutes
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django REST Framework Configuration
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # FlexiblePagination supports both page number (?page=2&page_size=50)
    # and limit/offset (?limit=50&offset=100) styles
    "DEFAULT_PAGINATION_CLASS": "app.pagination.FlexiblePagination",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "auth_manager.authentication.JWTCookieAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "djangorestframework_camel_case.render.CamelCaseJSONRenderer",
        "djangorestframework_camel_case.render.CamelCaseBrowsableAPIRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "djangorestframework_camel_case.parser.CamelCaseJSONParser",
        "djangorestframework_camel_case.parser.CamelCaseFormParser",
        "djangorestframework_camel_case.parser.CamelCaseMultiPartParser",
    ],
}


# Django Silk profiling settings
# SILKY_PYTHON_PROFILER = True
# SILKY_PYTHON_PROFILER_BINARY = True
SILKY_PYTHON_PROFILER_RESULT_PATH = "silk/profiler/"
SILKY_META = True

# drf-spectacular settings
SPECTACULAR_SETTINGS = {
    "TITLE": "Todo Lists API",
    "DESCRIPTION": "API for managing todo lists and todos",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "CAMELIZE_NAMES": True,
    "PREPROCESSING_HOOKS": [
        "drf_spectacular.hooks.preprocess_exclude_path_format",
    ],
    "POSTPROCESSING_HOOKS": [
        "drf_spectacular.contrib.djangorestframework_camel_case.camelize_serializer_fields",
    ],
    "ENUM_NAME_OVERRIDES": {
        "PriorityEnum": "todos.models.Todo.priority",
    },
}

# Audit Log settings
AUDIT_LOG_ASYNC = False  # Set to True to use Celery for async processing
AUDIT_LOG_EXCLUDED_PATHS = [
    "/health/",
    "/api/health/",
    "/static/",
    "/media/",
    "/__debug__/",
    "/silk/",
    "/admin/jsi18n/",
]
AUDIT_LOG_EXCLUDED_METHODS = []  # Empty = log all methods (except GET by default)
AUDIT_LOG_READS = False  # Set to True to also log GET requests
AUDIT_LOG_AUTO_CAPTURE = False  # Set to True to auto-capture all model changes
AUDIT_LOG_AUTO_CAPTURE_MODELS = []  # e.g., ['assets.Asset', 'workspaces.Workspace']
AUDIT_LOG_RETENTION_DAYS = 365  # How long to keep audit logs
PERMISSION_CACHE_TIMEOUT = 300  # 5 minutes

# AWS Configuration
AWS_REGION = os.environ.get("AWS_DEFAULT_REGION", "us-east-1")
AWS_KMS_KEY_ID = os.environ.get("AWS_KMS_KEY_ID")
AWS_KMS_ENDPOINT_URL = os.environ.get("AWS_KMS_ENDPOINT_URL")  # For LocalStack

# JWT Configuration (djangorestframework-simplejwt)
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# JWT Cookie settings
JWT_AUTH_COOKIE = "access_token"
JWT_AUTH_REFRESH_COOKIE = "refresh_token"
JWT_AUTH_SECURE = not DEBUG  # HTTPS only in production
JWT_AUTH_HTTPONLY = True
JWT_AUTH_SAMESITE = "Lax"

# Auth Manager settings
SHORT_TOKEN_EXPIRATION = 60 * 15  # 15 minutes for OneTimeToken
MAGIC_LINK_TOKEN_EXPIRATION_TIME = 60 * 60  # 1 hour for magic links
