# Generated by Django 6.0.1 on 2026-01-18 19:04

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.manager
import pgtrigger.compiler
import pgtrigger.migrations
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MFADevice',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='User-friendly name for this device', max_length=100)),
                ('_encrypted_secret', models.TextField(db_column='secret', help_text='KMS-encrypted TOTP secret key')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When the device was confirmed with a valid code', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this device was used for authentication', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='IdentityProvider',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description for this IdP')),
                ('enabled', models.BooleanField(default=True)),
                ('domains', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, help_text="List of email domains (e.g. ['example.com', 'test.com'])")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BackupCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(help_text='SHA-256 hash of the backup code', max_length=64)),
                ('used_at', models.DateTimeField(blank=True, help_text='When this code was used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_backup_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailDevice',
            fields=[
                ('mfadevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth_manager.mfadevice')),
                ('email', models.EmailField(blank=True, help_text="Email address for delivery (defaults to user's email if blank)", max_length=254)),
            ],
            options={
                'verbose_name': 'Email Device',
                'verbose_name_plural': 'Email Devices',
            },
            bases=('auth_manager.mfadevice',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SMSDevice',
            fields=[
                ('mfadevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth_manager.mfadevice')),
                ('phone_number', models.CharField(help_text='Phone number for SMS delivery (E.164 format)', max_length=20)),
            ],
            options={
                'verbose_name': 'SMS Device',
                'verbose_name_plural': 'SMS Devices',
            },
            bases=('auth_manager.mfadevice',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TOTPDevice',
            fields=[
                ('mfadevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth_manager.mfadevice')),
            ],
            options={
                'verbose_name': 'TOTP Device',
                'verbose_name_plural': 'TOTP Devices',
            },
            bases=('auth_manager.mfadevice',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failed_login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LocalIdentityProvider',
            fields=[
                ('identityprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth_manager.identityprovider')),
            ],
            options={
                'abstract': False,
            },
            bases=('auth_manager.identityprovider',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SAMLIdentityProvider',
            fields=[
                ('identityprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth_manager.identityprovider')),
                ('allow_autoenrollment', models.BooleanField(default=True, help_text='If true, users can be automatically created from SAML assertions.')),
                ('entity_id', models.CharField(max_length=512)),
                ('sso_url', models.URLField()),
                ('x509_cert', models.TextField()),
                ('metadata_url', models.URLField(blank=True)),
                ('attribute_mappings', models.JSONField(blank=True, default=dict, help_text='Mapping of IdP attributes to user fields.')),
            ],
            options={
                'abstract': False,
            },
            bases=('auth_manager.identityprovider',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='IdentityProviderUser',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('identity_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_provider_users', to='auth_manager.identityprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_provider_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='identityprovider',
            name='system_users',
            field=models.ManyToManyField(blank=True, help_text='System users associated with this identity provider.', related_name='identity_providers', through='auth_manager.IdentityProviderUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OneTimeToken',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, help_text='Django session key, if available', max_length=40, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address at login', null=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, help_text='State/Province', max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Raw user agent string', max_length=500)),
                ('device_type', models.CharField(blank=True, help_text='e.g., desktop, mobile, tablet', max_length=50)),
                ('browser', models.CharField(blank=True, help_text='Browser name and version', max_length=100)),
                ('operating_system', models.CharField(blank=True, help_text='OS name and version', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now_add=True, help_text='Last time this session was active')),
                ('logged_out_at', models.DateTimeField(blank=True, help_text='When the user explicitly logged out', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='emaildevice',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE auth_manager_mfadevice\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.mfadevice_ptr_id;\n                        RETURN NULL;\n                        ', hash='85c5420e5d6c91f12ac32e5fcb5f154ca663b39f', operation='DELETE', pgid='pgtrigger_soft_delete_b7a95', table='auth_manager_emaildevice', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='smsdevice',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE auth_manager_mfadevice\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.mfadevice_ptr_id;\n                        RETURN NULL;\n                        ', hash='c7cb3e607005b53734d743539abe0cd032f58625', operation='DELETE', pgid='pgtrigger_soft_delete_8e1e2', table='auth_manager_smsdevice', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='totpdevice',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE auth_manager_mfadevice\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.mfadevice_ptr_id;\n                        RETURN NULL;\n                        ', hash='0144330c7a9a53e3d58890d54f5c087e8832ce7d', operation='DELETE', pgid='pgtrigger_soft_delete_95e14', table='auth_manager_totpdevice', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='mfadevice',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'name'), name='unique_mfa_device_name_per_user'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='mfadevice',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            UPDATE auth_manager_mfadevice \n            SET deleted_at = NOW()\n            WHERE id = OLD.id;\n            RETURN NULL;\n            ', hash='3f50de1779e1a60ab316bd8c8b0680fce69560a1', operation='DELETE', pgid='pgtrigger_soft_delete_8a4d4', table='auth_manager_mfadevice', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='failedloginattempt',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            UPDATE auth_manager_failedloginattempt \n            SET deleted_at = NOW()\n            WHERE id = OLD.id;\n            RETURN NULL;\n            ', hash='35541646dd6cd1fd9f7052f6507c7e249740bb54', operation='DELETE', pgid='pgtrigger_soft_delete_1809b', table='auth_manager_failedloginattempt', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='localidentityprovider',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE auth_manager_identityprovider\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.identityprovider_ptr_id;\n                        RETURN NULL;\n                        ', hash='ee016edee0ddc20e2846ca57f5361aa786d49638', operation='DELETE', pgid='pgtrigger_soft_delete_7a71e', table='auth_manager_localidentityprovider', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='samlidentityprovider',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE auth_manager_identityprovider\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.identityprovider_ptr_id;\n                        RETURN NULL;\n                        ', hash='ac571b9ff3b5d7caeab8f06ee08fb9d3d3e3d0a7', operation='DELETE', pgid='pgtrigger_soft_delete_8c9cb', table='auth_manager_samlidentityprovider', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='identityprovideruser',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('identity_provider', 'user'), name='unique_identity_provider_user'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='identityprovideruser',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            UPDATE auth_manager_identityprovideruser \n            SET deleted_at = NOW()\n            WHERE id = OLD.id;\n            RETURN NULL;\n            ', hash='4ce790d257c38eb0347f81062ed418ab1bb33a3c', operation='DELETE', pgid='pgtrigger_soft_delete_8906c', table='auth_manager_identityprovideruser', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='identityprovider',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_identity_provider_name'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='identityprovider',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            UPDATE auth_manager_identityprovider \n            SET deleted_at = NOW()\n            WHERE id = OLD.id;\n            RETURN NULL;\n            ', hash='b5b7631ea3ca6b567c253479fb50d5051cfdd580', operation='DELETE', pgid='pgtrigger_soft_delete_4ce3d', table='auth_manager_identityprovider', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='onetimetoken',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            UPDATE auth_manager_onetimetoken \n            SET deleted_at = NOW()\n            WHERE id = OLD.id;\n            RETURN NULL;\n            ', hash='77e56690280f430a2e4d2dc4783670b2e583fa83', operation='DELETE', pgid='pgtrigger_soft_delete_ea212', table='auth_manager_onetimetoken', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', '-created_at'], name='auth_manage_user_id_32d19d_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_key'], name='auth_manage_session_2cdf99_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='usersession',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            UPDATE auth_manager_usersession \n            SET deleted_at = NOW()\n            WHERE id = OLD.id;\n            RETURN NULL;\n            ', hash='95a7680b80027a15dcb71bfa24f92b8570d59744', operation='DELETE', pgid='pgtrigger_soft_delete_4ed7a', table='auth_manager_usersession', when='BEFORE')),
        ),
    ]
