# Generated by Django 5.1 on 2025-08-18 18:27

import django.contrib.postgres.fields
import django.db.models.deletion
import mainapp.fields.immutable_uuid_field
import uuid
from django.conf import settings
from django.db import migrations, models


def initialize_identity_provider_instance(apps, schema_editor):
    LocalIdentityProvider = apps.get_model("auth_manager", "LocalIdentityProvider")
    # Get the polymorphic content type for LocalIdentityProvider
    ContentType = apps.get_model("contenttypes", "ContentType")
    local_idp_type = ContentType.objects.get_for_model(LocalIdentityProvider)

    LocalIdentityProvider.objects.create(
        name="Local Database",
        description="Uses the local database for user authentication.",
        polymorphic_ctype=local_idp_type,
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IdentityProvider",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="created_at")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="updated_at")),
                (
                    "global_id",
                    mainapp.fields.immutable_uuid_field.ImmutableUUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, help_text="Optional description for this IdP")),
                ("enabled", models.BooleanField(default=True)),
                (
                    "domains",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        default=list,
                        help_text="List of email domains (e.g. ['example.com', 'test.com'])",
                        size=None,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created_by",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="updated_by",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="LocalIdentityProvider",
            fields=[
                (
                    "identityprovider_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="auth_manager.identityprovider",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("auth_manager.identityprovider",),
        ),
        migrations.CreateModel(
            name="SAMLIdentityProvider",
            fields=[
                (
                    "identityprovider_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="auth_manager.identityprovider",
                    ),
                ),
                ("entity_id", models.CharField(max_length=512)),
                ("sso_url", models.URLField()),
                ("x509_cert", models.TextField()),
                ("metadata_url", models.URLField(blank=True)),
                (
                    "attribute_mappings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Mapping of IdP attributes to user fields, e.g. {'email': 'EmailAddress', 'first_name': 'FirstName'}",
                    ),
                ),
                (
                    "allow_autoenrollment",
                    models.BooleanField(
                        default=True, help_text="If true, users can be automatically created from SAML assertions."
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("auth_manager.identityprovider",),
        ),
        migrations.CreateModel(
            name="IdentityProviderUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "identity_provider",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="auth_manager.identityprovider"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("identity_provider", "user")},
            },
        ),
        migrations.RunPython(initialize_identity_provider_instance, migrations.RunPython.noop),
    ]
