# Generated by Django 6.0.1 on 2026-01-18

from django.db import migrations


def create_local_identity_provider(apps, schema_editor):
    IdentityProvider = apps.get_model("auth_manager", "IdentityProvider")
    ContentType = apps.get_model("contenttypes", "ContentType")

    # Get the content type for LocalIdentityProvider
    content_type = ContentType.objects.get(
        app_label="auth_manager",
        model="localidentityprovider",
    )

    # Check if a LocalIdentityProvider already exists (by checking content type)
    if IdentityProvider.all_objects.filter(polymorphic_ctype=content_type).exists():
        return

    # Create the parent IdentityProvider record
    idp = IdentityProvider.all_objects.create(
        name="Local",
        description="Local username and password authentication",
        enabled=True,
        domains=[],
        polymorphic_ctype=content_type,
    )

    # Create the child LocalIdentityProvider record using raw SQL
    # since the model from apps.get_model() doesn't have the manager
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute(
            "INSERT INTO auth_manager_localidentityprovider (identityprovider_ptr_id) VALUES (%s)",
            [idp.id],
        )


def remove_local_identity_provider(apps, schema_editor):
    IdentityProvider = apps.get_model("auth_manager", "IdentityProvider")
    IdentityProvider.all_objects.filter(name="Local").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("auth_manager", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_local_identity_provider,
            remove_local_identity_provider,
        ),
    ]
