# Generated by Django 5.1 on 2025-08-28 14:33

import django.db.models.deletion
import mainapp.fields.immutable_uuid_field
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_manager', '0001_Initializing_IdentityProvider_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='identityprovider',
            name='system_users',
            field=models.ManyToManyField(blank=True, help_text='System users associated with this identity provider (for auditing, ownership, or automation).', related_name='identity_providers', through='auth_manager.IdentityProviderUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OneTimeToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_id', mainapp.fields.immutable_uuid_field.ImmutableUUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
