# Generated by Django 6.0.1 on 2026-01-18 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_manager', '0002_create_local_identity_provider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailDevice',
        ),
    ]
