# Generated by Django 6.0.1 on 2026-01-10 00:35

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BaseAttributeValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['asset', 'field_definition__order'],
            },
        ),
        migrations.CreateModel(
            name='AssetAttributeDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('api_key', models.CharField(help_text='Key used in API serialization', max_length=100)),
                ('attribute_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('json', 'JSON')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_definitions', to='assets.assettype')),
            ],
            options={
                'ordering': ['asset_type', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('geohash', models.CharField(blank=True, db_index=True, help_text='Geohash of the geometry centroid', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assets.assettype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BooleanAttributeValue',
            fields=[
                ('baseattributevalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseattributevalue')),
                ('value', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('assets.baseattributevalue',),
        ),
        migrations.CreateModel(
            name='DateAttributeValue',
            fields=[
                ('baseattributevalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseattributevalue')),
                ('value', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('assets.baseattributevalue',),
        ),
        migrations.CreateModel(
            name='DateTimeAttributeValue',
            fields=[
                ('baseattributevalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseattributevalue')),
                ('value', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('assets.baseattributevalue',),
        ),
        migrations.CreateModel(
            name='JSONAttributeValue',
            fields=[
                ('baseattributevalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseattributevalue')),
                ('value', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('assets.baseattributevalue',),
        ),
        migrations.CreateModel(
            name='NumberAttributeValue',
            fields=[
                ('baseattributevalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseattributevalue')),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('assets.baseattributevalue',),
        ),
        migrations.CreateModel(
            name='TextAttributeValue',
            fields=[
                ('baseattributevalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseattributevalue')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('assets.baseattributevalue',),
        ),
        migrations.AddField(
            model_name='baseattributevalue',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='baseattributevalue',
            name='field_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='assets.assetattributedefinition'),
        ),
        migrations.AddField(
            model_name='baseattributevalue',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddConstraint(
            model_name='assetattributedefinition',
            constraint=models.UniqueConstraint(fields=('asset_type', 'name'), name='unique_asset_type_name'),
        ),
        migrations.AddConstraint(
            model_name='assetattributedefinition',
            constraint=models.UniqueConstraint(fields=('asset_type', 'api_key'), name='unique_asset_type_api_key'),
        ),
        migrations.AddConstraint(
            model_name='assetattributedefinition',
            constraint=models.UniqueConstraint(fields=('asset_type', 'order'), name='unique_asset_type_order'),
        ),
        migrations.AddConstraint(
            model_name='baseattributevalue',
            constraint=models.UniqueConstraint(fields=('asset', 'field_definition'), name='unique_asset_field_definition'),
        ),
    ]
