# Generated by Django 6.0.1 on 2026-01-11 19:45

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.db.models.manager
import pgtrigger.compiler
import pgtrigger.migrations
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAttributeValue',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['asset', 'attribute_type_attribute__order'],
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_types', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['workspace', 'name'],
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Centroid of geometry', null=True, srid=4326)),
                ('h3_index', models.CharField(blank=True, db_index=True, help_text='H3 index of the geometry centroid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assets.assettype')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AssetTypeAttribute',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('api_key', models.CharField(help_text='Key used in API serialization', max_length=100)),
                ('attribute_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('json', 'JSON')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='assets.assettype')),
            ],
            options={
                'ordering': ['asset_type', 'order', 'name'],
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BooleanAttributeValue',
            fields=[
                ('baseattributevalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseattributevalue')),
                ('value', models.BooleanField(blank=True, null=True)),
            ],
            bases=('assets.baseattributevalue',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DateAttributeValue',
            fields=[
                ('baseattributevalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseattributevalue')),
                ('value', models.DateField(blank=True, null=True)),
            ],
            bases=('assets.baseattributevalue',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DateTimeAttributeValue',
            fields=[
                ('baseattributevalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseattributevalue')),
                ('value', models.DateTimeField(blank=True, null=True)),
            ],
            bases=('assets.baseattributevalue',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='JSONAttributeValue',
            fields=[
                ('baseattributevalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseattributevalue')),
                ('value', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            bases=('assets.baseattributevalue',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='NumberAttributeValue',
            fields=[
                ('baseattributevalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseattributevalue')),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            bases=('assets.baseattributevalue',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TextAttributeValue',
            fields=[
                ('baseattributevalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseattributevalue')),
                ('value', models.TextField(blank=True, null=True)),
            ],
            bases=('assets.baseattributevalue',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='baseattributevalue',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='baseattributevalue',
            name='attribute_type_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='assets.assettypeattribute'),
        ),
        migrations.AddField(
            model_name='baseattributevalue',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddConstraint(
            model_name='assettype',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='unique_workspace_asset_type_name'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='assettype',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            UPDATE assets_assettype \n            SET deleted_at = NOW()\n            WHERE id = OLD.id;\n            RETURN NULL;\n            ', hash='03f084ea236c3fe6d7096db72227e48a8bee0899', operation='DELETE', pgid='pgtrigger_soft_delete_82b20', table='assets_assettype', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(name='001_update_location_on_geometry_change', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.location = ST_Centroid(NEW.geometry); RETURN NEW;', hash='4acd8fa4fac3d233f4bc392fd4d09874859ad43e', operation='UPDATE OR INSERT', pgid='pgtrigger_001_update_location_on_geometry_change_73cb8', table='assets_asset', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(name='002_update_h3_index_on_location_change', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n                IF NEW.location IS NOT NULL THEN\n                        NEW.h3_index = h3_latlng_to_cell(point(ST_Y(NEW.location), ST_X(NEW.location)), 15);\n                ELSE\n                    NEW.h3_index = '';\n                END IF;\n                RETURN NEW;\n                ", hash='741613ec449db4f839ff94a37516a7e6826767fa', operation='UPDATE OR INSERT', pgid='pgtrigger_002_update_h3_index_on_location_change_eb04c', table='assets_asset', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            UPDATE assets_asset \n            SET deleted_at = NOW()\n            WHERE id = OLD.id;\n            RETURN NULL;\n            ', hash='e8c93a84a014ed52ef7853a9d1ab3deb7644ed09', operation='DELETE', pgid='pgtrigger_soft_delete_6817c', table='assets_asset', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='assettypeattribute',
            constraint=models.UniqueConstraint(fields=('asset_type', 'name'), name='unique_asset_type_name'),
        ),
        migrations.AddConstraint(
            model_name='assettypeattribute',
            constraint=models.UniqueConstraint(fields=('asset_type', 'api_key'), name='unique_asset_type_api_key'),
        ),
        migrations.AddConstraint(
            model_name='assettypeattribute',
            constraint=models.UniqueConstraint(fields=('asset_type', 'order'), name='unique_asset_type_order'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='assettypeattribute',
            trigger=pgtrigger.compiler.Trigger(name='01_update_attribute_orders_after_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                    -- Use negative temporary values to avoid unique constraint violations\n                    UPDATE assets_assettypeattribute \n                    SET "order" = -("order" + 1000)\n                    WHERE asset_type_id = OLD.asset_type_id \n                    AND "order" > OLD."order";\n                    \n                    -- Now update to final values (decrement by 1)\n                    UPDATE assets_assettypeattribute \n                    SET "order" = -("order" + 1000) - 1\n                    WHERE asset_type_id = OLD.asset_type_id \n                    AND "order" < -1000;\n                    \n                    RETURN OLD;\n                ', hash='88913988dfd7c274efcc47f8ef728220b7e217fa', operation='DELETE', pgid='pgtrigger_01_update_attribute_orders_after_delete_aaa35', table='assets_assettypeattribute', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='assettypeattribute',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            UPDATE assets_assettypeattribute \n            SET deleted_at = NOW()\n            WHERE id = OLD.id;\n            RETURN NULL;\n            ', hash='e5325405ebda1d274ca5f7e080014bab048d3681', operation='DELETE', pgid='pgtrigger_soft_delete_8ae19', table='assets_assettypeattribute', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='jsonattributevalue',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE assets_baseattributevalue\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.baseattributevalue_ptr_id;\n                        RETURN NULL;\n                        ', hash='d9f5d223d06225572db7024faeec37e4001d3c69', operation='DELETE', pgid='pgtrigger_soft_delete_65ee7', table='assets_jsonattributevalue', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='baseattributevalue',
            constraint=models.UniqueConstraint(fields=('asset', 'attribute_type_attribute'), name='unique_asset_attribute_type_attribute'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='baseattributevalue',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            UPDATE assets_baseattributevalue \n            SET deleted_at = NOW()\n            WHERE id = OLD.id;\n            RETURN NULL;\n            ', hash='230378de4d1fb8f86f8fd23544516e075c12c5e5', operation='DELETE', pgid='pgtrigger_soft_delete_ff546', table='assets_baseattributevalue', when='BEFORE')),
        ),
    ]
