# Generated by Django 6.0.1 on 2026-01-13 17:29

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.db.models.manager
import pgtrigger.compiler
import pgtrigger.migrations
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('files_manager', '0001_initial'),
        ('organizations', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTypeAttributeChoice',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='Display label shown to users', max_length=255)),
                ('icon', models.CharField(blank=True, help_text="Icon identifier (e.g., 'mdi:check', 'fa:star', or URL to icon)", max_length=100)),
                ('color', models.CharField(blank=True, help_text="Color for the choice (e.g., '#FF5733', 'red', 'rgb(255,87,51)')", max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['asset_type_attribute', 'order', 'label'],
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BaseAssetTypeAttribute',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['asset_type', 'created_at'],
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BaseAttributeValue',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['asset', 'created_at'],
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BaseWorkspaceChoice',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_modifications', to='workspaces.workspace')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_types', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization', 'name'],
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Centroid of geometry', null=True, srid=4326)),
                ('h3_index', models.CharField(blank=True, db_index=True, help_text='H3 index of the geometry centroid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_folder', models.ForeignKey(blank=True, help_text='Default folder for file uploads related to this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_with_default', to='files_manager.directory')),
                ('organization', models.ForeignKey(help_text='Organization that owns this asset', on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='organizations.organization')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent asset for hierarchical relationships', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='assets.asset')),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assets.assettype')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BooleanAttributeChoice',
            fields=[
                ('assettypeattributechoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.assettypeattributechoice')),
                ('value', models.BooleanField()),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            bases=('assets.assettypeattributechoice',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DateAttributeChoice',
            fields=[
                ('assettypeattributechoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.assettypeattributechoice')),
                ('value', models.DateField()),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            bases=('assets.assettypeattributechoice',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DateTimeAttributeChoice',
            fields=[
                ('assettypeattributechoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.assettypeattributechoice')),
                ('value', models.DateTimeField()),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            bases=('assets.assettypeattributechoice',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='JSONAttributeChoice',
            fields=[
                ('assettypeattributechoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.assettypeattributechoice')),
                ('value', models.JSONField()),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            bases=('assets.assettypeattributechoice',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='NumberAttributeChoice',
            fields=[
                ('assettypeattributechoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.assettypeattributechoice')),
                ('value', models.FloatField()),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            bases=('assets.assettypeattributechoice',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TextAttributeChoice',
            fields=[
                ('assettypeattributechoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.assettypeattributechoice')),
                ('value', models.TextField()),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            bases=('assets.assettypeattributechoice',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GlobalAssetTypeAttribute',
            fields=[
                ('baseassettypeattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseassettypeattribute')),
                ('name', models.CharField(max_length=100)),
                ('api_key', models.CharField(help_text='Key used in API serialization', max_length=100)),
                ('attribute_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('json', 'JSON')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags for grouping attributes')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
            bases=('assets.baseassettypeattribute',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceHiddenAttribute',
            fields=[
                ('baseassettypeattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseassettypeattribute')),
            ],
            bases=('assets.baseassettypeattribute',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceLocalAssetTypeAttribute',
            fields=[
                ('baseassettypeattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseassettypeattribute')),
                ('name', models.CharField(max_length=100)),
                ('api_key', models.CharField(help_text='Key used in API serialization', max_length=100)),
                ('attribute_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('json', 'JSON')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags for grouping attributes')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['workspace', 'order', 'name'],
            },
            bases=('assets.baseassettypeattribute',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceOverrideAssetTypeAttribute',
            fields=[
                ('baseassettypeattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseassettypeattribute')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_required', models.BooleanField(blank=True, null=True)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
            bases=('assets.baseassettypeattribute',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='baseassettypeattribute',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='assets.assettype'),
        ),
        migrations.AddField(
            model_name='baseassettypeattribute',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='BooleanAttributeValue',
            fields=[
                ('baseattributevalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseattributevalue')),
                ('value', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            bases=('assets.baseattributevalue',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceAttributeValue',
            fields=[
                ('baseattributevalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseattributevalue')),
            ],
            options={
                'verbose_name': 'Choice Attribute Value',
                'verbose_name_plural': 'Choice Attribute Values',
            },
            bases=('assets.baseattributevalue',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DateAttributeValue',
            fields=[
                ('baseattributevalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseattributevalue')),
                ('value', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            bases=('assets.baseattributevalue',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DateTimeAttributeValue',
            fields=[
                ('baseattributevalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseattributevalue')),
                ('value', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            bases=('assets.baseattributevalue',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='JSONAttributeValue',
            fields=[
                ('baseattributevalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseattributevalue')),
                ('value', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            bases=('assets.baseattributevalue',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='NumberAttributeValue',
            fields=[
                ('baseattributevalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseattributevalue')),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            bases=('assets.baseattributevalue',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TextAttributeValue',
            fields=[
                ('baseattributevalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseattributevalue')),
                ('value', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            bases=('assets.baseattributevalue',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='baseattributevalue',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='baseattributevalue',
            name='asset_type_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='assets.baseassettypeattribute'),
        ),
        migrations.AddField(
            model_name='baseattributevalue',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='BaseWorkspaceExtensionChoice',
            fields=[
                ('baseworkspacechoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseworkspacechoice')),
                ('label', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            bases=('assets.baseworkspacechoice',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceChoiceOverride',
            fields=[
                ('baseworkspacechoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseworkspacechoice')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
            bases=('assets.baseworkspacechoice',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceHiddenChoice',
            fields=[
                ('baseworkspacechoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseworkspacechoice')),
            ],
            bases=('assets.baseworkspacechoice',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, help_text='User who added this asset to the workspace', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_workspace_assets', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to='assets.asset')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_assets', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceAssetType',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_owner', models.BooleanField(default=False, help_text='If true, this workspace owns the asset type and can modify it')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_asset_types', to='assets.assettype')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_asset_types', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['workspace', 'asset_type'],
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceAssetTypeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attribute_order', models.JSONField(blank=True, default=list, help_text='Ordered list of attribute UUIDs (GlobalAssetTypeAttribute and WorkspaceLocalAssetTypeAttribute)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_configs', to='assets.assettype')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_type_configs', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Workspace Asset Type Config',
                'verbose_name_plural': 'Workspace Asset Type Configs',
            },
        ),
        migrations.CreateModel(
            name='AssetCustomAttribute',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('api_key', models.CharField(help_text='Key used in API serialization', max_length=100)),
                ('attribute_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('json', 'JSON')], max_length=20)),
                ('value', models.JSONField(blank=True, help_text='The actual value of this custom attribute', null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_attributes', to='assets.asset')),
                ('workspace', models.ForeignKey(blank=True, help_text='If set, this custom attribute is only visible in this workspace', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_custom_attributes', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['asset', 'workspace', 'name'],
                'abstract': False,
                'default_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('asset', 'workspace', 'name'), name='unique_custom_attr_name'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('asset', 'workspace', 'api_key'), name='unique_custom_attr_api_key')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='assetcustomattribute',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            UPDATE assets_assetcustomattribute \n            SET deleted_at = NOW()\n            WHERE id = OLD.id;\n            RETURN NULL;\n            ', hash='bad819aa696d1fbbc8b5ce3754f71d2e950f0377', operation='DELETE', pgid='pgtrigger_soft_delete_a6fc6', table='assets_assetcustomattribute', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='assettype',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            UPDATE assets_assettype \n            SET deleted_at = NOW()\n            WHERE id = OLD.id;\n            RETURN NULL;\n            ', hash='03f084ea236c3fe6d7096db72227e48a8bee0899', operation='DELETE', pgid='pgtrigger_soft_delete_82b20', table='assets_assettype', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(name='001_update_location_on_geometry_change', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.location = ST_Centroid(NEW.geometry); RETURN NEW;', hash='4acd8fa4fac3d233f4bc392fd4d09874859ad43e', operation='UPDATE OR INSERT', pgid='pgtrigger_001_update_location_on_geometry_change_73cb8', table='assets_asset', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(name='002_update_h3_index_on_location_change', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n                IF NEW.location IS NOT NULL THEN\n                        NEW.h3_index = h3_latlng_to_cell(point(ST_Y(NEW.location), ST_X(NEW.location)), 15);\n                ELSE\n                    NEW.h3_index = '';\n                END IF;\n                RETURN NEW;\n                ", hash='741613ec449db4f839ff94a37516a7e6826767fa', operation='UPDATE OR INSERT', pgid='pgtrigger_002_update_h3_index_on_location_change_eb04c', table='assets_asset', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(name='003_prevent_circular_parent', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n                DECLARE\n                    current_parent_id UUID;\n                    max_depth INT := 100;\n                    depth INT := 0;\n                BEGIN\n                    -- Skip if no parent set\n                    IF NEW.parent_id IS NULL THEN\n                        RETURN NEW;\n                    END IF;\n\n                    -- Check self-reference\n                    IF NEW.parent_id = NEW.id THEN\n                        RAISE EXCEPTION 'An asset cannot be its own parent';\n                    END IF;\n\n                    -- Walk up the parent chain to detect cycles\n                    current_parent_id := NEW.parent_id;\n                    WHILE current_parent_id IS NOT NULL AND depth < max_depth LOOP\n                        -- Check if we've looped back to the asset being saved\n                        IF current_parent_id = NEW.id THEN\n                            RAISE EXCEPTION 'Circular parent relationship detected';\n                        END IF;\n\n                        -- Move to next parent\n                        SELECT parent_id INTO current_parent_id\n                        FROM assets_asset\n                        WHERE id = current_parent_id;\n\n                        depth := depth + 1;\n                    END LOOP;\n\n                    IF depth >= max_depth THEN\n                        RAISE EXCEPTION 'Parent hierarchy too deep (max % levels)', max_depth;\n                    END IF;\n\n                    RETURN NEW;\n                END;\n                ", hash='bc54cde91a02cf76141b2a696cf66b48b676bac2', operation='UPDATE OR INSERT', pgid='pgtrigger_003_prevent_circular_parent_7cad8', table='assets_asset', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            UPDATE assets_asset \n            SET deleted_at = NOW()\n            WHERE id = OLD.id;\n            RETURN NULL;\n            ', hash='e8c93a84a014ed52ef7853a9d1ab3deb7644ed09', operation='DELETE', pgid='pgtrigger_soft_delete_6817c', table='assets_asset', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='booleanattributechoice',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE assets_assettypeattributechoice\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.assettypeattributechoice_ptr_id;\n                        RETURN NULL;\n                        ', hash='925ed232437467360ec9e649a76956e6514a6abc', operation='DELETE', pgid='pgtrigger_soft_delete_bf5dd', table='assets_booleanattributechoice', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='dateattributechoice',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE assets_assettypeattributechoice\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.assettypeattributechoice_ptr_id;\n                        RETURN NULL;\n                        ', hash='58547364d60a49e30c1d39dfdea217de7dda1c19', operation='DELETE', pgid='pgtrigger_soft_delete_3f174', table='assets_dateattributechoice', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='datetimeattributechoice',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE assets_assettypeattributechoice\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.assettypeattributechoice_ptr_id;\n                        RETURN NULL;\n                        ', hash='6b8ea2ce5f0e6d40e678df93c5d37ca2ef628870', operation='DELETE', pgid='pgtrigger_soft_delete_4bef7', table='assets_datetimeattributechoice', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='jsonattributechoice',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE assets_assettypeattributechoice\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.assettypeattributechoice_ptr_id;\n                        RETURN NULL;\n                        ', hash='791f2ac054320f02bfbe1e19bad05da22791254c', operation='DELETE', pgid='pgtrigger_soft_delete_71069', table='assets_jsonattributechoice', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='numberattributechoice',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE assets_assettypeattributechoice\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.assettypeattributechoice_ptr_id;\n                        RETURN NULL;\n                        ', hash='cd2a8107275d7414480a8b6b7b216a3ee2d768b1', operation='DELETE', pgid='pgtrigger_soft_delete_19e5c', table='assets_numberattributechoice', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='textattributechoice',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE assets_assettypeattributechoice\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.assettypeattributechoice_ptr_id;\n                        RETURN NULL;\n                        ', hash='3ea609587fb4079b8e48aa4a4488cf643596ca12', operation='DELETE', pgid='pgtrigger_soft_delete_e93fb', table='assets_textattributechoice', when='BEFORE')),
        ),
        migrations.AddField(
            model_name='assettypeattributechoice',
            name='asset_type_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assets.globalassettypeattribute'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='globalassettypeattribute',
            trigger=pgtrigger.compiler.Trigger(name='unique_global_api_key_per_asset_type', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                    IF EXISTS (\n                        SELECT 1 \n                        FROM public.assets_globalassettypeattribute gata\n                        JOIN public.assets_baseassettypeattribute base ON gata.baseassettypeattribute_ptr_id = base.id\n                        WHERE base.asset_type_id = (\n                            SELECT asset_type_id FROM public.assets_baseassettypeattribute \n                            WHERE id = NEW.baseassettypeattribute_ptr_id\n                        )\n                        AND gata.api_key = NEW.api_key\n                        AND gata.baseassettypeattribute_ptr_id != NEW.baseassettypeattribute_ptr_id\n                        AND base.deleted_at IS NULL\n                    ) THEN\n                        RAISE EXCEPTION \'Duplicate api_key "%" for asset_type\', NEW.api_key;\n                    END IF;\n                    RETURN NEW;\n                ', hash='b63dd498dd4b9401ed8f9c8ad0c85a42493644df', operation='INSERT OR UPDATE', pgid='pgtrigger_unique_global_api_key_per_asset_type_0c319', table='assets_globalassettypeattribute', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='globalassettypeattribute',
            trigger=pgtrigger.compiler.Trigger(name='unique_global_name_per_asset_type', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                    IF EXISTS (\n                        SELECT 1 \n                        FROM public.assets_globalassettypeattribute gata\n                        JOIN public.assets_baseassettypeattribute base ON gata.baseassettypeattribute_ptr_id = base.id\n                        WHERE base.asset_type_id = (\n                            SELECT asset_type_id FROM public.assets_baseassettypeattribute \n                            WHERE id = NEW.baseassettypeattribute_ptr_id\n                        )\n                        AND gata.name = NEW.name\n                        AND gata.baseassettypeattribute_ptr_id != NEW.baseassettypeattribute_ptr_id\n                        AND base.deleted_at IS NULL\n                    ) THEN\n                        RAISE EXCEPTION \'Duplicate name "%" for asset_type\', NEW.name;\n                    END IF;\n                    RETURN NEW;\n                ', hash='56f22114083c0a09c9bb595971081170fb6bcac5', operation='INSERT OR UPDATE', pgid='pgtrigger_unique_global_name_per_asset_type_aa6c1', table='assets_globalassettypeattribute', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='globalassettypeattribute',
            trigger=pgtrigger.compiler.Trigger(name='01_update_base_attr_orders_after_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                    UPDATE public.assets_assettypeattribute \n                    SET "order" = -("order" + 1000)\n                    WHERE asset_type_id = OLD.asset_type_id \n                    AND "order" > OLD."order";\n                    \n                    UPDATE public.assets_assettypeattribute \n                    SET "order" = -("order" + 1000) - 1\n                    WHERE asset_type_id = OLD.asset_type_id \n                    AND "order" < -1000;\n                    \n                    RETURN OLD;\n                ', hash='58f5ff98c74feca76c2ffe1e4823da9d5257ee22', operation='DELETE', pgid='pgtrigger_01_update_base_attr_orders_after_delete_57561', table='assets_globalassettypeattribute', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='globalassettypeattribute',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE assets_baseassettypeattribute\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.baseassettypeattribute_ptr_id;\n                        RETURN NULL;\n                        ', hash='bf21314b422e464c715569eca44da08cf22d9ab9', operation='DELETE', pgid='pgtrigger_soft_delete_de98b', table='assets_globalassettypeattribute', when='BEFORE')),
        ),
        migrations.AddField(
            model_name='workspacehiddenattribute',
            name='hidden_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_in_workspaces', to='assets.baseassettypeattribute'),
        ),
        migrations.AddField(
            model_name='workspacehiddenattribute',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_attributes', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='workspacelocalassettypeattribute',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_attributes', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='workspaceoverrideassettypeattribute',
            name='base_attribute',
            field=models.ForeignKey(help_text='The base attribute this overrides', on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='assets.globalassettypeattribute'),
        ),
        migrations.AddField(
            model_name='workspaceoverrideassettypeattribute',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_overrides', to='workspaces.workspace'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='baseassettypeattribute',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            UPDATE assets_baseassettypeattribute \n            SET deleted_at = NOW()\n            WHERE id = OLD.id;\n            RETURN NULL;\n            ', hash='b7a9fb013381296832f240e414a38ce9209123bc', operation='DELETE', pgid='pgtrigger_soft_delete_8589d', table='assets_baseassettypeattribute', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='booleanattributevalue',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE assets_baseattributevalue\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.baseattributevalue_ptr_id;\n                        RETURN NULL;\n                        ', hash='7c6326c233ff653f3f6e863f5675c860bee9fa7c', operation='DELETE', pgid='pgtrigger_soft_delete_fecda', table='assets_booleanattributevalue', when='BEFORE')),
        ),
        migrations.AddField(
            model_name='choiceattributevalue',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attribute_values', to='assets.assettypeattributechoice'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='dateattributevalue',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE assets_baseattributevalue\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.baseattributevalue_ptr_id;\n                        RETURN NULL;\n                        ', hash='2eb9b80a1c5b008d9747a7fddf872bf4fe1d4e7d', operation='DELETE', pgid='pgtrigger_soft_delete_ace98', table='assets_dateattributevalue', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='datetimeattributevalue',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE assets_baseattributevalue\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.baseattributevalue_ptr_id;\n                        RETURN NULL;\n                        ', hash='e46afb82a52c2bd1b96e77e4e8549b4952f76410', operation='DELETE', pgid='pgtrigger_soft_delete_b111f', table='assets_datetimeattributevalue', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='jsonattributevalue',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE assets_baseattributevalue\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.baseattributevalue_ptr_id;\n                        RETURN NULL;\n                        ', hash='d9f5d223d06225572db7024faeec37e4001d3c69', operation='DELETE', pgid='pgtrigger_soft_delete_65ee7', table='assets_jsonattributevalue', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='numberattributevalue',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE assets_baseattributevalue\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.baseattributevalue_ptr_id;\n                        RETURN NULL;\n                        ', hash='08b975c578b18fb23b212b18c05e194a27afff2f', operation='DELETE', pgid='pgtrigger_soft_delete_54945', table='assets_numberattributevalue', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='textattributevalue',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE assets_baseattributevalue\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.baseattributevalue_ptr_id;\n                        RETURN NULL;\n                        ', hash='94c7366d3fdfa3fc1ee46e7953f28fbd2dec494d', operation='DELETE', pgid='pgtrigger_soft_delete_2dc58', table='assets_textattributevalue', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='baseattributevalue',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['asset_type_attribute', 'asset'], name='idx_attr_asset'),
        ),
        migrations.AddConstraint(
            model_name='baseattributevalue',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('asset', 'asset_type_attribute'), name='unique_asset_asset_type_attribute'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='baseattributevalue',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            UPDATE assets_baseattributevalue \n            SET deleted_at = NOW()\n            WHERE id = OLD.id;\n            RETURN NULL;\n            ', hash='230378de4d1fb8f86f8fd23544516e075c12c5e5', operation='DELETE', pgid='pgtrigger_soft_delete_ff546', table='assets_baseattributevalue', when='BEFORE')),
        ),
        migrations.CreateModel(
            name='BooleanExtensionChoice',
            fields=[
                ('baseworkspaceextensionchoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseworkspaceextensionchoice')),
                ('value', models.BooleanField()),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            bases=('assets.baseworkspaceextensionchoice',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DateExtensionChoice',
            fields=[
                ('baseworkspaceextensionchoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseworkspaceextensionchoice')),
                ('value', models.DateField()),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            bases=('assets.baseworkspaceextensionchoice',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DateTimeExtensionChoice',
            fields=[
                ('baseworkspaceextensionchoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseworkspaceextensionchoice')),
                ('value', models.DateTimeField()),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            bases=('assets.baseworkspaceextensionchoice',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='JSONExtensionChoice',
            fields=[
                ('baseworkspaceextensionchoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseworkspaceextensionchoice')),
                ('value', models.JSONField()),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            bases=('assets.baseworkspaceextensionchoice',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='NumberExtensionChoice',
            fields=[
                ('baseworkspaceextensionchoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseworkspaceextensionchoice')),
                ('value', models.FloatField()),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            bases=('assets.baseworkspaceextensionchoice',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TextExtensionChoice',
            fields=[
                ('baseworkspaceextensionchoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseworkspaceextensionchoice')),
                ('value', models.TextField()),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            bases=('assets.baseworkspaceextensionchoice',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='baseworkspaceextensionchoice',
            name='extension_attribute',
            field=models.ForeignKey(blank=True, help_text='Extension attribute this choice belongs to (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assets.workspacelocalassettypeattribute'),
        ),
        migrations.AddField(
            model_name='baseworkspaceextensionchoice',
            name='global_attribute',
            field=models.ForeignKey(blank=True, help_text='Global attribute this choice extends (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extension_choices', to='assets.globalassettypeattribute'),
        ),
        migrations.AddField(
            model_name='workspacechoiceoverride',
            name='base_choice',
            field=models.ForeignKey(help_text='The base choice this overrides', on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='assets.assettypeattributechoice'),
        ),
        migrations.AddField(
            model_name='workspacehiddenchoice',
            name='base_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_in_workspaces', to='assets.assettypeattributechoice'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='baseworkspacechoice',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            UPDATE assets_baseworkspacechoice \n            SET deleted_at = NOW()\n            WHERE id = OLD.id;\n            RETURN NULL;\n            ', hash='df63e9c8fd2295883cce1e0bc26f9df38c07b354', operation='DELETE', pgid='pgtrigger_soft_delete_0ecec', table='assets_baseworkspacechoice', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='workspaceasset',
            constraint=models.UniqueConstraint(fields=('workspace', 'asset'), name='unique_workspace_asset'),
        ),
        migrations.AddConstraint(
            model_name='workspaceassettype',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'asset_type'), name='unique_workspace_asset_type'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='workspaceassettype',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            UPDATE assets_workspaceassettype \n            SET deleted_at = NOW()\n            WHERE id = OLD.id;\n            RETURN NULL;\n            ', hash='fa99c25c8de24801f6d36f30e3c93d868f0fab46', operation='DELETE', pgid='pgtrigger_soft_delete_f88b7', table='assets_workspaceassettype', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='workspaceassettypeconfig',
            constraint=models.UniqueConstraint(fields=('workspace', 'asset_type'), name='unique_workspace_asset_type_config'),
        ),
        migrations.AddConstraint(
            model_name='assettypeattributechoice',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('asset_type_attribute', 'order'), name='unique_ata_choice_order'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='assettypeattributechoice',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            UPDATE assets_assettypeattributechoice \n            SET deleted_at = NOW()\n            WHERE id = OLD.id;\n            RETURN NULL;\n            ', hash='90ffb1cf5c252e65593de8e3375804b3e12f9250', operation='DELETE', pgid='pgtrigger_soft_delete_487df', table='assets_assettypeattributechoice', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='workspacehiddenattribute',
            constraint=models.UniqueConstraint(fields=('hidden_attribute', 'workspace'), name='unique_hidden_per_workspace'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='workspacehiddenattribute',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE assets_baseassettypeattribute\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.baseassettypeattribute_ptr_id;\n                        RETURN NULL;\n                        ', hash='84553a474cb2621c7bf339fd7a3e8fe83839e86f', operation='DELETE', pgid='pgtrigger_soft_delete_cbcee', table='assets_workspacehiddenattribute', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='workspacelocalassettypeattribute',
            trigger=pgtrigger.compiler.Trigger(name='unique_extension_api_key_per_workspace', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                    -- Check against other extensions\n                    IF EXISTS (\n                        SELECT 1 \n                        FROM public.assets_workspacelocalassettypeattribute wea\n                        JOIN public.assets_baseassettypeattribute base ON wea.baseassettypeattribute_ptr_id = base.id\n                        WHERE wea.workspace_id = NEW.workspace_id\n                        AND base.asset_type_id = (\n                            SELECT asset_type_id FROM public.assets_baseassettypeattribute \n                            WHERE id = NEW.baseassettypeattribute_ptr_id\n                        )\n                        AND wea.api_key = NEW.api_key\n                        AND wea.baseassettypeattribute_ptr_id != NEW.baseassettypeattribute_ptr_id\n                        AND base.deleted_at IS NULL\n                    ) THEN\n                        RAISE EXCEPTION \'Duplicate api_key "%" for workspace and asset_type\', NEW.api_key;\n                    END IF;\n                    \n                    -- Check against global attributes for same asset_type\n                    IF EXISTS (\n                        SELECT 1 \n                        FROM public.assets_globalassettypeattribute gata\n                        JOIN public.assets_baseassettypeattribute base ON gata.baseassettypeattribute_ptr_id = base.id\n                        WHERE base.asset_type_id = (\n                            SELECT asset_type_id FROM public.assets_baseassettypeattribute \n                            WHERE id = NEW.baseassettypeattribute_ptr_id\n                        )\n                        AND gata.api_key = NEW.api_key\n                        AND base.deleted_at IS NULL\n                    ) THEN\n                        RAISE EXCEPTION \'api_key "%" conflicts with a global attribute\', NEW.api_key;\n                    END IF;\n                    RETURN NEW;\n                ', hash='6a52723db527db506040fdad5d58f47617f66b94', operation='INSERT OR UPDATE', pgid='pgtrigger_unique_extension_api_key_per_workspace_dfc33', table='assets_workspacelocalassettypeattribute', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='workspacelocalassettypeattribute',
            trigger=pgtrigger.compiler.Trigger(name='unique_extension_name_per_workspace', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                    -- Check against other extensions\n                    IF EXISTS (\n                        SELECT 1 \n                        FROM public.assets_workspacelocalassettypeattribute wea\n                        JOIN public.assets_baseassettypeattribute base ON wea.baseassettypeattribute_ptr_id = base.id\n                        WHERE wea.workspace_id = NEW.workspace_id\n                        AND base.asset_type_id = (\n                            SELECT asset_type_id FROM public.assets_baseassettypeattribute \n                            WHERE id = NEW.baseassettypeattribute_ptr_id\n                        )\n                        AND wea.name = NEW.name\n                        AND wea.baseassettypeattribute_ptr_id != NEW.baseassettypeattribute_ptr_id\n                        AND base.deleted_at IS NULL\n                    ) THEN\n                        RAISE EXCEPTION \'Duplicate name "%" for workspace and asset_type\', NEW.name;\n                    END IF;\n                    \n                    -- Check against override names in same workspace\n                    IF EXISTS (\n                        SELECT 1 \n                        FROM public.assets_workspaceoverrideassettypeattribute wao\n                        JOIN public.assets_baseassettypeattribute base ON wao.baseassettypeattribute_ptr_id = base.id\n                        WHERE wao.workspace_id = NEW.workspace_id\n                        AND base.asset_type_id = (\n                            SELECT asset_type_id FROM public.assets_baseassettypeattribute \n                            WHERE id = NEW.baseassettypeattribute_ptr_id\n                        )\n                        AND wao.name = NEW.name\n                        AND wao.name IS NOT NULL\n                        AND base.deleted_at IS NULL\n                    ) THEN\n                        RAISE EXCEPTION \'Name "%" conflicts with an override in this workspace\', NEW.name;\n                    END IF;\n                    \n                    -- Check against global attributes for same asset_type\n                    IF EXISTS (\n                        SELECT 1 \n                        FROM public.assets_globalassettypeattribute gata\n                        JOIN public.assets_baseassettypeattribute base ON gata.baseassettypeattribute_ptr_id = base.id\n                        WHERE base.asset_type_id = (\n                            SELECT asset_type_id FROM public.assets_baseassettypeattribute \n                            WHERE id = NEW.baseassettypeattribute_ptr_id\n                        )\n                        AND gata.name = NEW.name\n                        AND base.deleted_at IS NULL\n                    ) THEN\n                        RAISE EXCEPTION \'Name "%" conflicts with a global attribute\', NEW.name;\n                    END IF;\n                    RETURN NEW;\n                ', hash='08c54fd02a7373dbee351291b70acdf25f47364c', operation='INSERT OR UPDATE', pgid='pgtrigger_unique_extension_name_per_workspace_fb9f3', table='assets_workspacelocalassettypeattribute', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='workspacelocalassettypeattribute',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE assets_baseassettypeattribute\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.baseassettypeattribute_ptr_id;\n                        RETURN NULL;\n                        ', hash='80590d3ef0bd76c5ad580c805cce85b6496a9722', operation='DELETE', pgid='pgtrigger_soft_delete_88351', table='assets_workspacelocalassettypeattribute', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='workspaceoverrideassettypeattribute',
            constraint=models.UniqueConstraint(fields=('base_attribute', 'workspace'), name='unique_override_per_workspace'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='workspaceoverrideassettypeattribute',
            trigger=pgtrigger.compiler.Trigger(name='unique_override_name_vs_extensions', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                    -- Only check if name is being set\n                    IF NEW.name IS NOT NULL THEN\n                        -- Check against extension names in same workspace\n                        IF EXISTS (\n                            SELECT 1 \n                            FROM public.assets_workspacelocalassettypeattribute wea\n                            JOIN public.assets_baseassettypeattribute base ON wea.baseassettypeattribute_ptr_id = base.id\n                            WHERE wea.workspace_id = NEW.workspace_id\n                            AND base.asset_type_id = (\n                                SELECT asset_type_id FROM public.assets_baseassettypeattribute \n                                WHERE id = NEW.baseassettypeattribute_ptr_id\n                            )\n                            AND wea.name = NEW.name\n                            AND base.deleted_at IS NULL\n                        ) THEN\n                            RAISE EXCEPTION \'Name "%" conflicts with an extension in this workspace\', NEW.name;\n                        END IF;\n                        \n                        -- Check against other override names in same workspace\n                        IF EXISTS (\n                            SELECT 1 \n                            FROM public.assets_workspaceoverrideassettypeattribute wao\n                            JOIN public.assets_baseassettypeattribute base ON wao.baseassettypeattribute_ptr_id = base.id\n                            WHERE wao.workspace_id = NEW.workspace_id\n                            AND base.asset_type_id = (\n                                SELECT asset_type_id FROM public.assets_baseassettypeattribute \n                                WHERE id = NEW.baseassettypeattribute_ptr_id\n                            )\n                            AND wao.name = NEW.name\n                            AND wao.baseassettypeattribute_ptr_id != NEW.baseassettypeattribute_ptr_id\n                            AND base.deleted_at IS NULL\n                        ) THEN\n                            RAISE EXCEPTION \'Name "%" conflicts with another override in this workspace\', NEW.name;\n                        END IF;\n                    END IF;\n                    RETURN NEW;\n                ', hash='13c6e339b1dd72df8df3e5f8888d11eba180cd49', operation='INSERT OR UPDATE', pgid='pgtrigger_unique_override_name_vs_extensions_028fd', table='assets_workspaceoverrideassettypeattribute', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='workspaceoverrideassettypeattribute',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE assets_baseassettypeattribute\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.baseassettypeattribute_ptr_id;\n                        RETURN NULL;\n                        ', hash='decd4ad697d63608ad912d7a75549f437860f7e8', operation='DELETE', pgid='pgtrigger_soft_delete_eb0b7', table='assets_workspaceoverrideassettypeattribute', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='choiceattributevalue',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE assets_baseattributevalue\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.baseattributevalue_ptr_id;\n                        RETURN NULL;\n                        ', hash='394ffed02126d2e2fbcdb7cbe03b8b8d488a8a0f', operation='DELETE', pgid='pgtrigger_soft_delete_ed594', table='assets_choiceattributevalue', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='booleanextensionchoice',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE assets_baseworkspaceextensionchoice\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.baseworkspaceextensionchoice_ptr_id;\n                        RETURN NULL;\n                        ', hash='9410f02c7932a138e7c44cede8a29a5e5c7a9a03', operation='DELETE', pgid='pgtrigger_soft_delete_0e8d1', table='assets_booleanextensionchoice', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='dateextensionchoice',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE assets_baseworkspaceextensionchoice\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.baseworkspaceextensionchoice_ptr_id;\n                        RETURN NULL;\n                        ', hash='53f7808fa3d57391dd19878ef3f1cd39c1b1dd3f', operation='DELETE', pgid='pgtrigger_soft_delete_dda29', table='assets_dateextensionchoice', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='datetimeextensionchoice',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE assets_baseworkspaceextensionchoice\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.baseworkspaceextensionchoice_ptr_id;\n                        RETURN NULL;\n                        ', hash='1b0bc34237ed642bb418e6abad393b9cb02aa386', operation='DELETE', pgid='pgtrigger_soft_delete_68ccb', table='assets_datetimeextensionchoice', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='jsonextensionchoice',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE assets_baseworkspaceextensionchoice\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.baseworkspaceextensionchoice_ptr_id;\n                        RETURN NULL;\n                        ', hash='ef1cf7732074b22432337681c61fd2cdeb5e6840', operation='DELETE', pgid='pgtrigger_soft_delete_2eb1d', table='assets_jsonextensionchoice', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='numberextensionchoice',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE assets_baseworkspaceextensionchoice\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.baseworkspaceextensionchoice_ptr_id;\n                        RETURN NULL;\n                        ', hash='769f348a1638f05fa7c533a6004d47318ea447a6', operation='DELETE', pgid='pgtrigger_soft_delete_22088', table='assets_numberextensionchoice', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='textextensionchoice',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE assets_baseworkspaceextensionchoice\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.baseworkspaceextensionchoice_ptr_id;\n                        RETURN NULL;\n                        ', hash='eb2eede0448ab058a75505193024818a92d1bdfe', operation='DELETE', pgid='pgtrigger_soft_delete_9e5e7', table='assets_textextensionchoice', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='baseworkspaceextensionchoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('extension_attribute__isnull', True), ('global_attribute__isnull', False)), models.Q(('extension_attribute__isnull', False), ('global_attribute__isnull', True)), _connector='OR'), name='extension_choice_has_one_attribute'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='baseworkspaceextensionchoice',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE assets_baseworkspacechoice\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.baseworkspacechoice_ptr_id;\n                        RETURN NULL;\n                        ', hash='422c3e49c1afc805eb39e1d385f5c200392db83c', operation='DELETE', pgid='pgtrigger_soft_delete_7321d', table='assets_baseworkspaceextensionchoice', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='workspacechoiceoverride',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE assets_baseworkspacechoice\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.baseworkspacechoice_ptr_id;\n                        RETURN NULL;\n                        ', hash='e4585962b8eef146c6075ea543b65c6b8ea90127', operation='DELETE', pgid='pgtrigger_soft_delete_e2dcb', table='assets_workspacechoiceoverride', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='workspacehiddenchoice',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE assets_baseworkspacechoice\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.baseworkspacechoice_ptr_id;\n                        RETURN NULL;\n                        ', hash='ca2f1ebefa40a5e0cc5e1f52b907e814b40b1dcc', operation='DELETE', pgid='pgtrigger_soft_delete_727bf', table='assets_workspacehiddenchoice', when='BEFORE')),
        ),
    ]
