# Generated by Django 6.0.1 on 2026-01-14 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('files_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='default_folder',
            field=models.ForeignKey(blank=True, help_text='Default folder for file uploads related to this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_with_default', to='files_manager.directory'),
        ),
    ]
