# Generated by Django 6.0.1 on 2026-01-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceoverrideassettypeattribute',
            name='api_key',
            field=models.CharField(default=1, help_text='Key used in API serialization', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workspaceoverrideassettypeattribute',
            name='attribute_type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('json', 'JSON')], max_length=20, null=True),
        ),
    ]
