# Generated by Django 6.0.1 on 2026-01-10 08:04

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booleanattributevalue',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dateattributevalue',
            options={},
        ),
        migrations.AlterModelOptions(
            name='datetimeattributevalue',
            options={},
        ),
        migrations.AlterModelOptions(
            name='jsonattributevalue',
            options={},
        ),
        migrations.AlterModelOptions(
            name='numberattributevalue',
            options={},
        ),
        migrations.AlterModelOptions(
            name='textattributevalue',
            options={},
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Centroid of geometry', null=True, srid=4326),
        ),
    ]
