# Generated by Django 6.0.1 on 2026-01-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='baseattributevalue',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['asset_type_attribute', 'asset'], name='idx_attr_asset'),
        ),
    ]
