# Generated by Django 6.0.1 on 2026-01-12 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_baseattributevalue_idx_attr_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent asset for hierarchical relationships', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='assets.asset'),
        ),
    ]
