# Generated by Django 6.0.1 on 2026-01-13 02:22

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='globalassettypeattribute',
            name='unique_global_api_key_per_asset_type',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='globalassettypeattribute',
            name='unique_global_name_per_asset_type',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='globalassettypeattribute',
            name='01_update_base_attr_orders_after_delete',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='workspaceattributeoverride',
            name='unique_override_name_vs_extensions',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='workspaceextensionattribute',
            name='unique_extension_api_key_per_workspace',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='workspaceextensionattribute',
            name='unique_extension_name_per_workspace',
        ),
        migrations.RemoveField(
            model_name='workspaceextensionattribute',
            name='is_hidden',
        ),
        migrations.AlterField(
            model_name='baseassettypeattribute',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='assets.assettype'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='globalassettypeattribute',
            trigger=pgtrigger.compiler.Trigger(name='unique_global_api_key_per_asset_type', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                    IF EXISTS (\n                        SELECT 1 \n                        FROM public.assets_globalassettypeattribute gata\n                        JOIN public.assets_baseassettypeattribute base ON gata.baseassettypeattribute_ptr_id = base.id\n                        WHERE base.asset_type_id = (\n                            SELECT asset_type_id FROM public.assets_baseassettypeattribute \n                            WHERE id = NEW.baseassettypeattribute_ptr_id\n                        )\n                        AND gata.api_key = NEW.api_key\n                        AND gata.baseassettypeattribute_ptr_id != NEW.baseassettypeattribute_ptr_id\n                        AND base.deleted_at IS NULL\n                    ) THEN\n                        RAISE EXCEPTION \'Duplicate api_key "%" for asset_type\', NEW.api_key;\n                    END IF;\n                    RETURN NEW;\n                ', hash='b63dd498dd4b9401ed8f9c8ad0c85a42493644df', operation='INSERT OR UPDATE', pgid='pgtrigger_unique_global_api_key_per_asset_type_0c319', table='assets_globalassettypeattribute', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='globalassettypeattribute',
            trigger=pgtrigger.compiler.Trigger(name='unique_global_name_per_asset_type', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                    IF EXISTS (\n                        SELECT 1 \n                        FROM public.assets_globalassettypeattribute gata\n                        JOIN public.assets_baseassettypeattribute base ON gata.baseassettypeattribute_ptr_id = base.id\n                        WHERE base.asset_type_id = (\n                            SELECT asset_type_id FROM public.assets_baseassettypeattribute \n                            WHERE id = NEW.baseassettypeattribute_ptr_id\n                        )\n                        AND gata.name = NEW.name\n                        AND gata.baseassettypeattribute_ptr_id != NEW.baseassettypeattribute_ptr_id\n                        AND base.deleted_at IS NULL\n                    ) THEN\n                        RAISE EXCEPTION \'Duplicate name "%" for asset_type\', NEW.name;\n                    END IF;\n                    RETURN NEW;\n                ', hash='56f22114083c0a09c9bb595971081170fb6bcac5', operation='INSERT OR UPDATE', pgid='pgtrigger_unique_global_name_per_asset_type_aa6c1', table='assets_globalassettypeattribute', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='globalassettypeattribute',
            trigger=pgtrigger.compiler.Trigger(name='01_update_base_attr_orders_after_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                    UPDATE public.assets_assettypeattribute \n                    SET "order" = -("order" + 1000)\n                    WHERE asset_type_id = OLD.asset_type_id \n                    AND "order" > OLD."order";\n                    \n                    UPDATE public.assets_assettypeattribute \n                    SET "order" = -("order" + 1000) - 1\n                    WHERE asset_type_id = OLD.asset_type_id \n                    AND "order" < -1000;\n                    \n                    RETURN OLD;\n                ', hash='58f5ff98c74feca76c2ffe1e4823da9d5257ee22', operation='DELETE', pgid='pgtrigger_01_update_base_attr_orders_after_delete_57561', table='assets_globalassettypeattribute', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='workspaceattributeoverride',
            trigger=pgtrigger.compiler.Trigger(name='unique_override_name_vs_extensions', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                    -- Only check if name is being set\n                    IF NEW.name IS NOT NULL THEN\n                        -- Check against extension names in same workspace\n                        IF EXISTS (\n                            SELECT 1 \n                            FROM public.assets_workspaceextensionattribute wea\n                            JOIN public.assets_baseassettypeattribute base ON wea.baseassettypeattribute_ptr_id = base.id\n                            WHERE wea.workspace_id = NEW.workspace_id\n                            AND base.asset_type_id = (\n                                SELECT asset_type_id FROM public.assets_baseassettypeattribute \n                                WHERE id = NEW.baseassettypeattribute_ptr_id\n                            )\n                            AND wea.name = NEW.name\n                            AND base.deleted_at IS NULL\n                        ) THEN\n                            RAISE EXCEPTION \'Name "%" conflicts with an extension in this workspace\', NEW.name;\n                        END IF;\n                        \n                        -- Check against other override names in same workspace\n                        IF EXISTS (\n                            SELECT 1 \n                            FROM public.assets_workspaceattributeoverride wao\n                            JOIN public.assets_baseassettypeattribute base ON wao.baseassettypeattribute_ptr_id = base.id\n                            WHERE wao.workspace_id = NEW.workspace_id\n                            AND base.asset_type_id = (\n                                SELECT asset_type_id FROM public.assets_baseassettypeattribute \n                                WHERE id = NEW.baseassettypeattribute_ptr_id\n                            )\n                            AND wao.name = NEW.name\n                            AND wao.baseassettypeattribute_ptr_id != NEW.baseassettypeattribute_ptr_id\n                            AND base.deleted_at IS NULL\n                        ) THEN\n                            RAISE EXCEPTION \'Name "%" conflicts with another override in this workspace\', NEW.name;\n                        END IF;\n                    END IF;\n                    RETURN NEW;\n                ', hash='8561597c18c8d29c5b344af75e32d5d75364a302', operation='INSERT OR UPDATE', pgid='pgtrigger_unique_override_name_vs_extensions_0d435', table='assets_workspaceattributeoverride', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='workspaceextensionattribute',
            trigger=pgtrigger.compiler.Trigger(name='unique_extension_api_key_per_workspace', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                    -- Check against other extensions\n                    IF EXISTS (\n                        SELECT 1 \n                        FROM public.assets_workspaceextensionattribute wea\n                        JOIN public.assets_baseassettypeattribute base ON wea.baseassettypeattribute_ptr_id = base.id\n                        WHERE wea.workspace_id = NEW.workspace_id\n                        AND base.asset_type_id = (\n                            SELECT asset_type_id FROM public.assets_baseassettypeattribute \n                            WHERE id = NEW.baseassettypeattribute_ptr_id\n                        )\n                        AND wea.api_key = NEW.api_key\n                        AND wea.baseassettypeattribute_ptr_id != NEW.baseassettypeattribute_ptr_id\n                        AND base.deleted_at IS NULL\n                    ) THEN\n                        RAISE EXCEPTION \'Duplicate api_key "%" for workspace and asset_type\', NEW.api_key;\n                    END IF;\n                    \n                    -- Check against global attributes for same asset_type\n                    IF EXISTS (\n                        SELECT 1 \n                        FROM public.assets_globalassettypeattribute gata\n                        JOIN public.assets_baseassettypeattribute base ON gata.baseassettypeattribute_ptr_id = base.id\n                        WHERE base.asset_type_id = (\n                            SELECT asset_type_id FROM public.assets_baseassettypeattribute \n                            WHERE id = NEW.baseassettypeattribute_ptr_id\n                        )\n                        AND gata.api_key = NEW.api_key\n                        AND base.deleted_at IS NULL\n                    ) THEN\n                        RAISE EXCEPTION \'api_key "%" conflicts with a global attribute\', NEW.api_key;\n                    END IF;\n                    RETURN NEW;\n                ', hash='7845050827d382b6e428af11311a0115ca458ac6', operation='INSERT OR UPDATE', pgid='pgtrigger_unique_extension_api_key_per_workspace_ad4f2', table='assets_workspaceextensionattribute', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='workspaceextensionattribute',
            trigger=pgtrigger.compiler.Trigger(name='unique_extension_name_per_workspace', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                    -- Check against other extensions\n                    IF EXISTS (\n                        SELECT 1 \n                        FROM public.assets_workspaceextensionattribute wea\n                        JOIN public.assets_baseassettypeattribute base ON wea.baseassettypeattribute_ptr_id = base.id\n                        WHERE wea.workspace_id = NEW.workspace_id\n                        AND base.asset_type_id = (\n                            SELECT asset_type_id FROM public.assets_baseassettypeattribute \n                            WHERE id = NEW.baseassettypeattribute_ptr_id\n                        )\n                        AND wea.name = NEW.name\n                        AND wea.baseassettypeattribute_ptr_id != NEW.baseassettypeattribute_ptr_id\n                        AND base.deleted_at IS NULL\n                    ) THEN\n                        RAISE EXCEPTION \'Duplicate name "%" for workspace and asset_type\', NEW.name;\n                    END IF;\n                    \n                    -- Check against override names in same workspace\n                    IF EXISTS (\n                        SELECT 1 \n                        FROM public.assets_workspaceattributeoverride wao\n                        JOIN public.assets_baseassettypeattribute base ON wao.baseassettypeattribute_ptr_id = base.id\n                        WHERE wao.workspace_id = NEW.workspace_id\n                        AND base.asset_type_id = (\n                            SELECT asset_type_id FROM public.assets_baseassettypeattribute \n                            WHERE id = NEW.baseassettypeattribute_ptr_id\n                        )\n                        AND wao.name = NEW.name\n                        AND wao.name IS NOT NULL\n                        AND base.deleted_at IS NULL\n                    ) THEN\n                        RAISE EXCEPTION \'Name "%" conflicts with an override in this workspace\', NEW.name;\n                    END IF;\n                    \n                    -- Check against global attributes for same asset_type\n                    IF EXISTS (\n                        SELECT 1 \n                        FROM public.assets_globalassettypeattribute gata\n                        JOIN public.assets_baseassettypeattribute base ON gata.baseassettypeattribute_ptr_id = base.id\n                        WHERE base.asset_type_id = (\n                            SELECT asset_type_id FROM public.assets_baseassettypeattribute \n                            WHERE id = NEW.baseassettypeattribute_ptr_id\n                        )\n                        AND gata.name = NEW.name\n                        AND base.deleted_at IS NULL\n                    ) THEN\n                        RAISE EXCEPTION \'Name "%" conflicts with a global attribute\', NEW.name;\n                    END IF;\n                    RETURN NEW;\n                ', hash='5afc4d01500b455cc069f9aa860080f80ac24306', operation='INSERT OR UPDATE', pgid='pgtrigger_unique_extension_name_per_workspace_018c2', table='assets_workspaceextensionattribute', when='BEFORE')),
        ),
    ]
