# Generated by Django 6.0.1 on 2026-01-10 10:32

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_booleanattributevalue_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='geohash',
            field=models.CharField(blank=True, db_index=True, help_text='H3 index of the geometry centroid', max_length=20),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(name='update_location_on_geometry_change', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.location = ST_Centroid(NEW.geometry); RETURN NEW;', hash='705f2ac5d4ca5adaeeb7ba54f3db0d38af248f9b', operation='UPDATE OR INSERT', pgid='pgtrigger_update_location_on_geometry_change_286ab', table='assets_asset', when='BEFORE')),
        ),
    ]
