# Generated by Django 6.0.1 on 2026-01-13 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_workspaceoverrideassettypeattribute_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettypeattributechoice',
            name='asset_type_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_choices', to='assets.baseassettypeattribute'),
        ),
    ]
