# Generated by Django 6.0.1 on 2026-01-14 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='organization',
            field=models.ForeignKey(help_text='Organization that owns this asset', on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='asset',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent asset for hierarchical relationships', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetcustomattribute',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_attributes', to='assets.asset'),
        ),
    ]
