# Generated by Django 6.0.1 on 2026-01-13 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_assettypeattributechoice_asset_type_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettypeattributechoice',
            name='asset_type_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assets.baseassettypeattribute'),
        ),
        migrations.AlterField(
            model_name='baseworkspaceextensionchoice',
            name='extension_attribute',
            field=models.ForeignKey(blank=True, help_text='Extension attribute this choice belongs to (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_extension_choices', to='assets.workspacelocalassettypeattribute'),
        ),
    ]
