# Generated by Django 6.0.1 on 2026-01-13 15:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_remove_globalassettypeattribute_unique_global_api_key_per_asset_type_and_more'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspaceextensionattribute',
            options={'ordering': ['workspace', 'name']},
        ),
        migrations.RemoveField(
            model_name='workspaceattributeoverride',
            name='order',
        ),
        migrations.RemoveField(
            model_name='workspaceextensionattribute',
            name='order',
        ),
        migrations.CreateModel(
            name='WorkspaceAssetTypeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attribute_order', models.JSONField(blank=True, default=list, help_text='Ordered list of attribute UUIDs (GlobalAssetTypeAttribute and WorkspaceExtensionAttribute)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_configs', to='assets.assettype')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_type_configs', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Workspace Asset Type Config',
                'verbose_name_plural': 'Workspace Asset Type Configs',
                'constraints': [models.UniqueConstraint(fields=('workspace', 'asset_type'), name='unique_workspace_asset_type_config')],
            },
        ),
    ]
