# Generated by Django 6.0.1 on 2026-01-10 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_geohash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='geohash',
            new_name='h3_index',
        ),
    ]
