# Generated by Django 6.0.1 on 2026-01-12 04:51

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_add_parent_to_asset'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='default_folder',
            field=models.ForeignKey(blank=True, help_text='Default folder for file uploads related to this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_with_default', to='files.directory'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(name='003_prevent_circular_parent', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n                DECLARE\n                    current_parent_id UUID;\n                    max_depth INT := 100;\n                    depth INT := 0;\n                BEGIN\n                    -- Skip if no parent set\n                    IF NEW.parent_id IS NULL THEN\n                        RETURN NEW;\n                    END IF;\n\n                    -- Check self-reference\n                    IF NEW.parent_id = NEW.id THEN\n                        RAISE EXCEPTION 'An asset cannot be its own parent';\n                    END IF;\n\n                    -- Walk up the parent chain to detect cycles\n                    current_parent_id := NEW.parent_id;\n                    WHILE current_parent_id IS NOT NULL AND depth < max_depth LOOP\n                        -- Check if we've looped back to the asset being saved\n                        IF current_parent_id = NEW.id THEN\n                            RAISE EXCEPTION 'Circular parent relationship detected';\n                        END IF;\n\n                        -- Move to next parent\n                        SELECT parent_id INTO current_parent_id\n                        FROM assets_asset\n                        WHERE id = current_parent_id;\n\n                        depth := depth + 1;\n                    END LOOP;\n\n                    IF depth >= max_depth THEN\n                        RAISE EXCEPTION 'Parent hierarchy too deep (max % levels)', max_depth;\n                    END IF;\n\n                    RETURN NEW;\n                END;\n                ", hash='bc54cde91a02cf76141b2a696cf66b48b676bac2', operation='UPDATE OR INSERT', pgid='pgtrigger_003_prevent_circular_parent_7cad8', table='assets_asset', when='BEFORE')),
        ),
    ]
