# Generated by Django 6.0.1 on 2026-01-14 20:18

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_initial'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='workspaceoverrideassettypeattribute',
            trigger=pgtrigger.compiler.Trigger(name='prevent_override_of_global_locked_attributes', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                    IF EXISTS (\n                        SELECT 1 \n                        FROM public.assets_globalassettypeattribute gata\n                        JOIN public.assets_baseassettypeattribute base ON gata.baseassettypeattribute_ptr_id = base.id\n                        WHERE gata.id = NEW.base_attribute_id\n                        AND gata.locked_to_global = TRUE\n                        AND base.deleted_at IS NULL\n                    ) THEN\n                        RAISE EXCEPTION \'Cannot create override for attribute "%" as it is locked to global\',\n                            (SELECT name FROM public.assets_globalassettypeattribute WHERE id = NEW.base_attribute_id);\n                    END IF;\n                    RETURN NEW;\n                ', hash='a752193847a1e2edbb8344a224b699b06f5182f2', operation='INSERT', pgid='pgtrigger_prevent_override_of_global_locked_attributes_5356b', table='assets_workspaceoverrideassettypeattribute', when='BEFORE')),
        ),
    ]
