# Generated by Django 6.0.1 on 2026-01-12 22:27

import django.db.models.deletion
import django.db.models.manager
import pgtrigger.compiler
import pgtrigger.migrations
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_asset_default_folder_and_more'),
        ('organizations', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceAssetType',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_owner', models.BooleanField(default=False, help_text='If true, this workspace owns the asset type and can modify it')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['workspace', 'asset_type'],
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='assettype',
            options={'default_manager_name': 'all_objects', 'ordering': ['organization', 'name']},
        ),
        migrations.AlterModelOptions(
            name='assettypeattribute',
            options={'default_manager_name': 'all_objects', 'ordering': ['asset_type', 'workspace', 'order', 'name']},
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='assettypeattribute',
            name='01_update_attribute_orders_after_delete',
        ),
        migrations.RemoveConstraint(
            model_name='assettype',
            name='unique_workspace_asset_type_name',
        ),
        migrations.RemoveConstraint(
            model_name='assettypeattribute',
            name='unique_asset_type_name',
        ),
        migrations.RemoveConstraint(
            model_name='assettypeattribute',
            name='unique_asset_type_api_key',
        ),
        migrations.RemoveConstraint(
            model_name='assettypeattribute',
            name='unique_asset_type_order',
        ),
        migrations.AddField(
            model_name='asset',
            name='organization',
            field=models.ForeignKey(default='b7a1185e-8f1a-4aef-a651-f3bf82450b02', help_text='Organization that owns this asset', on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='organizations.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assettype',
            name='organization',
            field=models.ForeignKey(default='b7a1185e-8f1a-4aef-a651-f3bf82450b02', on_delete=django.db.models.deletion.CASCADE, related_name='asset_types', to='organizations.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assettypeattribute',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='If set, this is a workspace-specific extension field', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_type_attribute_extensions', to='workspaces.workspace'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='assettypeattribute',
            trigger=pgtrigger.compiler.Trigger(name='01_update_attribute_orders_after_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                    -- Use negative temporary values to avoid unique constraint violations\n                    UPDATE assets_assettypeattribute \n                    SET "order" = -("order" + 1000)\n                    WHERE asset_type_id = OLD.asset_type_id \n                    AND (workspace_id = OLD.workspace_id OR (workspace_id IS NULL AND OLD.workspace_id IS NULL))\n                    AND "order" > OLD."order";\n                    \n                    -- Now update to final values (decrement by 1)\n                    UPDATE assets_assettypeattribute \n                    SET "order" = -("order" + 1000) - 1\n                    WHERE asset_type_id = OLD.asset_type_id \n                    AND (workspace_id = OLD.workspace_id OR (workspace_id IS NULL AND OLD.workspace_id IS NULL))\n                    AND "order" < -1000;\n                    \n                    RETURN OLD;\n                ', hash='5547adbcd36e0190ce04c21d28abb50350c7d1ad', operation='DELETE', pgid='pgtrigger_01_update_attribute_orders_after_delete_aaa35', table='assets_assettypeattribute', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='assettypeattribute',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('asset_type', 'workspace', 'name'), name='unique_asset_type_workspace_name'),
        ),
        migrations.AddConstraint(
            model_name='assettypeattribute',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('asset_type', 'workspace', 'api_key'), name='unique_asset_type_workspace_api_key'),
        ),
        migrations.AddConstraint(
            model_name='assettypeattribute',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('asset_type', 'workspace', 'order'), name='unique_asset_type_workspace_order'),
        ),
        migrations.AddField(
            model_name='workspaceasset',
            name='added_by',
            field=models.ForeignKey(blank=True, help_text='User who added this asset to the workspace', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_workspace_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspaceasset',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='workspaceasset',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_assets', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='workspaceassettype',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_asset_types', to='assets.assettype'),
        ),
        migrations.AddField(
            model_name='workspaceassettype',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_asset_types', to='workspaces.workspace'),
        ),
        migrations.RemoveField(
            model_name='assettype',
            name='workspace',
        ),
        migrations.AddConstraint(
            model_name='workspaceasset',
            constraint=models.UniqueConstraint(fields=('workspace', 'asset'), name='unique_workspace_asset'),
        ),
        migrations.AddConstraint(
            model_name='workspaceassettype',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'asset_type'), name='unique_workspace_asset_type'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='workspaceassettype',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            UPDATE assets_workspaceassettype \n            SET deleted_at = NOW()\n            WHERE id = OLD.id;\n            RETURN NULL;\n            ', hash='fa99c25c8de24801f6d36f30e3c93d868f0fab46', operation='DELETE', pgid='pgtrigger_soft_delete_f88b7', table='assets_workspaceassettype', when='BEFORE')),
        ),
    ]
