# Generated by Django 6.0.1 on 2026-01-10 20:12

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_rename_geohash_asset_h3_index'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseattributevalue',
            options={'ordering': ['asset', 'attribute_type_attribute__order']},
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='update_location_on_geometry_change',
        ),
        migrations.RemoveConstraint(
            model_name='baseattributevalue',
            name='unique_asset_field_definition',
        ),
        migrations.RenameField(
            model_name='baseattributevalue',
            old_name='field_definition',
            new_name='attribute_type_attribute',
        ),
        migrations.AlterField(
            model_name='assetattributedefinition',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='assets.assettype'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(name='001_update_location_on_geometry_change', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.location = ST_Centroid(NEW.geometry); RETURN NEW;', hash='4acd8fa4fac3d233f4bc392fd4d09874859ad43e', operation='UPDATE OR INSERT', pgid='pgtrigger_001_update_location_on_geometry_change_73cb8', table='assets_asset', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(name='002_update_h3_index_on_location_change', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n                IF NEW.location IS NOT NULL THEN\n                        NEW.h3_index = h3_latlng_to_cell(point(ST_Y(NEW.location), ST_X(NEW.location)), 15);\n                ELSE\n                    NEW.h3_index = '';\n                END IF;\n                RETURN NEW;\n                ", hash='741613ec449db4f839ff94a37516a7e6826767fa', operation='UPDATE OR INSERT', pgid='pgtrigger_002_update_h3_index_on_location_change_eb04c', table='assets_asset', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='baseattributevalue',
            constraint=models.UniqueConstraint(fields=('asset', 'attribute_type_attribute'), name='unique_asset_attribute_type_attribute'),
        ),
    ]
