# Generated by Django 6.0.1 on 2026-01-14 02:57

import django.db.models.deletion
import django.db.models.manager
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_assettypeattributechoice_asset_type_attribute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkAttributeChoice',
            fields=[
                ('assettypeattributechoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.assettypeattributechoice')),
                ('value', models.URLField(max_length=2000)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            bases=('assets.assettypeattributechoice',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LinkAttributeValue',
            fields=[
                ('baseattributevalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseattributevalue')),
                ('value', models.URLField(blank=True, max_length=2000)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            bases=('assets.baseattributevalue',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LinkExtensionChoice',
            fields=[
                ('baseworkspaceextensionchoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseworkspaceextensionchoice')),
                ('value', models.URLField(max_length=2000)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            bases=('assets.baseworkspaceextensionchoice',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='assetcustomattribute',
            name='attribute_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('json', 'JSON'), ('link', 'Link')], max_length=20),
        ),
        migrations.AlterField(
            model_name='globalassettypeattribute',
            name='attribute_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('json', 'JSON'), ('link', 'Link')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workspacelocalassettypeattribute',
            name='attribute_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('json', 'JSON'), ('link', 'Link')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workspaceoverrideassettypeattribute',
            name='attribute_type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('json', 'JSON'), ('link', 'Link')], max_length=20, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='linkattributechoice',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE assets_assettypeattributechoice\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.assettypeattributechoice_ptr_id;\n                        RETURN NULL;\n                        ', hash='53d3b77da002c2cb841f9c3bf25bb6df2b3abd41', operation='DELETE', pgid='pgtrigger_soft_delete_a065f', table='assets_linkattributechoice', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='linkattributevalue',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE assets_baseattributevalue\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.baseattributevalue_ptr_id;\n                        RETURN NULL;\n                        ', hash='58515fa04a02497c227401c91d64a46131c80dc5', operation='DELETE', pgid='pgtrigger_soft_delete_1f3e3', table='assets_linkattributevalue', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='linkextensionchoice',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE assets_baseworkspaceextensionchoice\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.baseworkspaceextensionchoice_ptr_id;\n                        RETURN NULL;\n                        ', hash='59626422c95dcf94e74de487be717a4533a56318', operation='DELETE', pgid='pgtrigger_soft_delete_dc836', table='assets_linkextensionchoice', when='BEFORE')),
        ),
    ]
