# Generated by Django 6.0.1 on 2026-01-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_add_link_attribute_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkattributechoice',
            old_name='value',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='linkattributevalue',
            old_name='value',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='linkextensionchoice',
            old_name='value',
            new_name='url',
        ),
        migrations.AddField(
            model_name='linkattributechoice',
            name='display_text',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='linkattributevalue',
            name='display_text',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='linkextensionchoice',
            name='display_text',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
