# Generated by Django 6.0.1 on 2026-01-15 00:12

import django.db.models.deletion
import django.db.models.manager
import pgtrigger.compiler
import pgtrigger.migrations
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_workspaceoverrideassettypeattribute_prevent_override_of_global_locked_attributes'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceAttributeValueOverride',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workspace Attribute Value Override',
                'verbose_name_plural': 'Workspace Attribute Value Overrides',
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='workspaceoverrideassettypeattribute',
            name='prevent_override_of_global_locked_attributes',
        ),
        migrations.RemoveConstraint(
            model_name='baseattributevalue',
            name='unique_asset_asset_type_attribute',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='workspaceoverrideassettypeattribute',
            trigger=pgtrigger.compiler.Trigger(name='prevent_override_of_global_locked_attributes', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                    IF EXISTS (\n                        SELECT 1 \n                        FROM public.assets_globalassettypeattribute gata\n                        JOIN public.assets_baseassettypeattribute base ON gata.baseassettypeattribute_ptr_id = base.id\n                        WHERE base.id = NEW.base_attribute_id\n                        AND gata.locked_to_global = TRUE\n                        AND base.deleted_at IS NULL\n                    ) THEN\n                        RAISE EXCEPTION \'Cannot create override for attribute "%" as it is locked to global\',\n                            (SELECT base.name \n                             FROM public.assets_globalassettypeattribute gata\n                             JOIN public.assets_baseassettypeattribute base ON gata.baseassettypeattribute_ptr_id = base.id\n                             WHERE base.id = NEW.base_attribute_id);\n                    END IF;\n                    RETURN NEW;\n                ', hash='e9eabf9bf6b015101b3c1f83d03de81a06c2fa78', operation='INSERT', pgid='pgtrigger_prevent_override_of_global_locked_attributes_5356b', table='assets_workspaceoverrideassettypeattribute', when='BEFORE')),
        ),
        migrations.AddConstraint(
            model_name='baseattributevalue',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('asset', 'asset_type_attribute'), name='unique_asset_attribute'),
        ),
        migrations.AddField(
            model_name='workspaceattributevalueoverride',
            name='asset_type_attribute',
            field=models.ForeignKey(help_text='The attribute definition this override applies to', on_delete=django.db.models.deletion.CASCADE, related_name='value_overrides', to='assets.baseassettypeattribute'),
        ),
        migrations.AddField(
            model_name='workspaceattributevalueoverride',
            name='base_value',
            field=models.ForeignKey(help_text='The original/global value being overridden', on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='assets.baseattributevalue'),
        ),
        migrations.AddField(
            model_name='workspaceattributevalueoverride',
            name='override_value',
            field=models.ForeignKey(help_text='The workspace-specific override value', on_delete=django.db.models.deletion.CASCADE, related_name='overrides_base', to='assets.baseattributevalue'),
        ),
        migrations.AddField(
            model_name='workspaceattributevalueoverride',
            name='workspace',
            field=models.ForeignKey(help_text='The workspace this override applies to', on_delete=django.db.models.deletion.CASCADE, related_name='attribute_value_overrides', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='workspaceattributevalueoverride',
            index=models.Index(fields=['workspace', 'asset_type_attribute'], name='assets_work_workspa_6b8fa3_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceattributevalueoverride',
            index=models.Index(fields=['base_value'], name='assets_work_base_va_b14c5f_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspaceattributevalueoverride',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('base_value', 'workspace'), name='unique_base_value_workspace_override'),
        ),
        migrations.AddConstraint(
            model_name='workspaceattributevalueoverride',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('override_value',), name='unique_override_value'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='workspaceattributevalueoverride',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            UPDATE assets_workspaceattributevalueoverride \n            SET deleted_at = NOW()\n            WHERE id = OLD.id;\n            RETURN NULL;\n            ', hash='15c0fd3b8c40a7369d5a12ec985f6235e5a1bb65', operation='DELETE', pgid='pgtrigger_soft_delete_5c867', table='assets_workspaceattributevalueoverride', when='BEFORE')),
        ),
    ]
