# Generated by Django 6.0.1 on 2026-01-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_workspaceasset_workspaceassettype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettypeattribute',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='If true, this attribute is hidden in this workspace'),
        ),
    ]
