# Generated by Django 6.0.1 on 2026-01-10 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_rename_field_definition_to_attribute'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssetAttributeDefinition',
            new_name='AssetTypeAttribute',
        ),
    ]
