# Generated by Django 6.0.1 on 2026-01-15 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_workspaceattributevalueoverride_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceattributevalueoverride',
            name='base_value',
            field=models.ForeignKey(blank=True, help_text='The original/global value being overridden', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='assets.baseattributevalue'),
        ),
    ]
