# Generated by Django 6.0.1 on 2026-01-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_add_is_hidden_to_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettypeattribute',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of tags for grouping attributes'),
        ),
    ]
