# Generated by Django 6.0.1 on 2026-01-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_update_link_with_display_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalassettypeattribute',
            name='unit',
            field=models.CharField(blank=True, help_text="Unit for number attributes (e.g., 'kg', 'm', 'degC'). Uses Pint unit syntax.", max_length=50),
        ),
        migrations.AddField(
            model_name='workspacelocalassettypeattribute',
            name='unit',
            field=models.CharField(blank=True, help_text="Unit for number attributes (e.g., 'kg', 'm', 'degC'). Uses Pint unit syntax.", max_length=50),
        ),
        migrations.AddField(
            model_name='workspaceoverrideassettypeattribute',
            name='unit',
            field=models.CharField(blank=True, help_text='Override unit for number attributes. Null means use base value.', max_length=50, null=True),
        ),
    ]
