# Generated by Django 6.0.1 on 2026-01-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_add_unit_to_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalassettypeattribute',
            name='cannot_override',
            field=models.BooleanField(default=False, help_text='If true, this attribute cannot be overridden by workspaces'),
        ),
        migrations.AddField(
            model_name='globalassettypeattribute',
            name='locked_to_global',
            field=models.BooleanField(default=False, help_text='If true, attribute values are locked to the global defaults and cannot be modified per workspace'),
        ),
    ]
