# Generated by Django 6.0.1 on 2026-01-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_add_tags_to_asset_type_attribute'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assettypeattribute',
            options={'default_manager_name': 'all_objects', 'ordering': ['asset_type', 'workspace', 'is_hidden', 'order', 'name']},
        ),
        migrations.RemoveConstraint(
            model_name='assettypeattribute',
            name='unique_asset_type_workspace_order',
        ),
        migrations.AddConstraint(
            model_name='assettypeattribute',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('asset_type', 'workspace', 'is_hidden', 'order'), name='unique_asset_type_workspace_hidden_order'),
        ),
    ]
