# Generated by Django 6.0.1 on 2026-01-15 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_workspaceattributevalueoverride_base_value'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='baseattributevalue',
            name='unique_asset_attribute',
        ),
    ]
