# Generated by Django 6.0.1 on 2026-01-13 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_update_order_constraint_include_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettypeattribute',
            name='base_attribute',
            field=models.ForeignKey(blank=True, help_text='If set, this is a workspace-specific override of a base attribute', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='assets.assettypeattribute'),
        ),
    ]
