# Generated by Django 6.0.1 on 2026-01-17 03:28

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_remove_baseattributevalue_unique_asset_attribute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assettypeattributechoice',
            options={'default_manager_name': 'all_objects', 'ordering': ['asset_type_attribute', 'order']},
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='asset',
            name='001_update_location_on_geometry_change',
        ),
        migrations.RemoveField(
            model_name='assettypeattributechoice',
            name='label',
        ),
        migrations.RemoveField(
            model_name='baseworkspaceextensionchoice',
            name='label',
        ),
        migrations.RemoveField(
            model_name='workspacechoiceoverride',
            name='label',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='asset',
            trigger=pgtrigger.compiler.Trigger(name='001_update_location_on_geometry_change', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n                IF ST_GeometryType(NEW.geometry) = 'ST_LineString' THEN\n                    NEW.location = ST_LineInterpolatePoint(NEW.geometry, 0.5);\n                ELSE\n                    NEW.location = ST_Centroid(NEW.geometry);\n                END IF;\n                RETURN NEW;\n                ", hash='86e360dfe492128ecef448aec390d9f726c9d106', operation='UPDATE OR INSERT', pgid='pgtrigger_001_update_location_on_geometry_change_73cb8', table='assets_asset', when='BEFORE')),
        ),
    ]
