# Generated by Django 6.0.1 on 2026-01-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_add_base_attribute_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettypeattribute',
            name='is_hide_only',
            field=models.BooleanField(default=False, help_text='If true, this override exists solely to hide the base attribute (no other changes)'),
        ),
    ]
