# Generated by Django 6.0.1 on 2026-01-17 03:35

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_alter_assettypeattributechoice_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booleanattributechoice',
            name='assettypeattributechoice_ptr',
        ),
        migrations.RemoveField(
            model_name='booleanextensionchoice',
            name='baseworkspaceextensionchoice_ptr',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='assettypeattributechoice',
            trigger=pgtrigger.compiler.Trigger(name='prevent_boolean_attribute_choices', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n                    IF EXISTS (\n                        SELECT 1\n                        FROM public.assets_baseassettypeattribute base\n                        WHERE base.id = NEW.asset_type_attribute_id\n                        AND base.attribute_type = 'boolean'\n                    ) THEN\n                        RAISE EXCEPTION 'Boolean attributes cannot have choices';\n                    END IF;\n                    RETURN NEW;\n                ", hash='2c1a1e5cd30e1c3e92b149d30e54d87fde411aaf', operation='INSERT', pgid='pgtrigger_prevent_boolean_attribute_choices_c8c5c', table='assets_assettypeattributechoice', when='BEFORE')),
        ),
        migrations.DeleteModel(
            name='BooleanAttributeChoice',
        ),
        migrations.DeleteModel(
            name='BooleanExtensionChoice',
        ),
    ]
