# Generated by Django 6.0.1 on 2026-01-17 04:07

import django.db.models.manager
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_remove_booleanattributechoice_assettypeattributechoice_ptr_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dateattributechoice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='datetimeattributechoice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='jsonattributechoice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='linkattributechoice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='numberattributechoice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='textattributechoice',
            options={},
        ),
        migrations.AlterModelManagers(
            name='dateattributechoice',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='datetimeattributechoice',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='jsonattributechoice',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='linkattributechoice',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='numberattributechoice',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='textattributechoice',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='assettypeattributechoice',
            name='prevent_boolean_attribute_choices',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='assettypeattributechoice',
            trigger=pgtrigger.compiler.Trigger(name='prevent_boolean_attribute_choices', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n                    -- Check GlobalAssetTypeAttribute\n                    IF EXISTS (\n                        SELECT 1\n                        FROM public.assets_globalassettypeattribute gata\n                        WHERE gata.baseassettypeattribute_ptr_id = NEW.asset_type_attribute_id\n                        AND gata.attribute_type = 'boolean'\n                    ) THEN\n                        RAISE EXCEPTION 'Boolean attributes cannot have choices';\n                    END IF;\n                    -- Check WorkspaceLocalAssetTypeAttribute\n                    IF EXISTS (\n                        SELECT 1\n                        FROM public.assets_workspacelocalassettypeattribute wla\n                        WHERE wla.baseassettypeattribute_ptr_id = NEW.asset_type_attribute_id\n                        AND wla.attribute_type = 'boolean'\n                    ) THEN\n                        RAISE EXCEPTION 'Boolean attributes cannot have choices';\n                    END IF;\n                    RETURN NEW;\n                ", hash='00fb946cea3ef0a50f21744a15c52edf53e11a46', operation='INSERT', pgid='pgtrigger_prevent_boolean_attribute_choices_c8c5c', table='assets_assettypeattributechoice', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='dateattributechoice',
            trigger=pgtrigger.compiler.Trigger(name='prevent_duplicate_date_choice', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n                    IF EXISTS (\n                        SELECT 1\n                        FROM public.assets_dateattributechoice dc\n                        JOIN public.assets_assettypeattributechoice base ON dc.assettypeattributechoice_ptr_id = base.id\n                        WHERE base.asset_type_attribute_id = (\n                            SELECT asset_type_attribute_id FROM public.assets_assettypeattributechoice WHERE id = NEW.assettypeattributechoice_ptr_id\n                        )\n                        AND dc.value = NEW.value\n                        AND dc.assettypeattributechoice_ptr_id != NEW.assettypeattributechoice_ptr_id\n                        AND base.deleted_at IS NULL\n                    ) THEN\n                        RAISE EXCEPTION 'A choice with this value already exists for this attribute';\n                    END IF;\n                    RETURN NEW;\n                ", hash='4e27498bb3b2163ba5a0081e7672cd9e9ab69745', operation='INSERT OR UPDATE', pgid='pgtrigger_prevent_duplicate_date_choice_3ffe0', table='assets_dateattributechoice', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='datetimeattributechoice',
            trigger=pgtrigger.compiler.Trigger(name='prevent_duplicate_datetime_choice', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n                    IF EXISTS (\n                        SELECT 1\n                        FROM public.assets_datetimeattributechoice dtc\n                        JOIN public.assets_assettypeattributechoice base ON dtc.assettypeattributechoice_ptr_id = base.id\n                        WHERE base.asset_type_attribute_id = (\n                            SELECT asset_type_attribute_id FROM public.assets_assettypeattributechoice WHERE id = NEW.assettypeattributechoice_ptr_id\n                        )\n                        AND dtc.value = NEW.value\n                        AND dtc.assettypeattributechoice_ptr_id != NEW.assettypeattributechoice_ptr_id\n                        AND base.deleted_at IS NULL\n                    ) THEN\n                        RAISE EXCEPTION 'A choice with this value already exists for this attribute';\n                    END IF;\n                    RETURN NEW;\n                ", hash='0ab3924727f2f598061efcc324ab72d39bf6c894', operation='INSERT OR UPDATE', pgid='pgtrigger_prevent_duplicate_datetime_choice_dbf75', table='assets_datetimeattributechoice', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='jsonattributechoice',
            trigger=pgtrigger.compiler.Trigger(name='prevent_duplicate_json_choice', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n                    IF EXISTS (\n                        SELECT 1\n                        FROM public.assets_jsonattributechoice jc\n                        JOIN public.assets_assettypeattributechoice base ON jc.assettypeattributechoice_ptr_id = base.id\n                        WHERE base.asset_type_attribute_id = (\n                            SELECT asset_type_attribute_id FROM public.assets_assettypeattributechoice WHERE id = NEW.assettypeattributechoice_ptr_id\n                        )\n                        AND jc.value = NEW.value\n                        AND jc.assettypeattributechoice_ptr_id != NEW.assettypeattributechoice_ptr_id\n                        AND base.deleted_at IS NULL\n                    ) THEN\n                        RAISE EXCEPTION 'A choice with this value already exists for this attribute';\n                    END IF;\n                    RETURN NEW;\n                ", hash='e253950bd54d92202b95d8e208dac4dfb75ec7bd', operation='INSERT OR UPDATE', pgid='pgtrigger_prevent_duplicate_json_choice_f46c1', table='assets_jsonattributechoice', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='linkattributechoice',
            trigger=pgtrigger.compiler.Trigger(name='prevent_duplicate_link_choice', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n                    IF EXISTS (\n                        SELECT 1\n                        FROM public.assets_linkattributechoice lc\n                        JOIN public.assets_assettypeattributechoice base ON lc.assettypeattributechoice_ptr_id = base.id\n                        WHERE base.asset_type_attribute_id = (\n                            SELECT asset_type_attribute_id FROM public.assets_assettypeattributechoice WHERE id = NEW.assettypeattributechoice_ptr_id\n                        )\n                        AND lc.url = NEW.url\n                        AND lc.assettypeattributechoice_ptr_id != NEW.assettypeattributechoice_ptr_id\n                        AND base.deleted_at IS NULL\n                    ) THEN\n                        RAISE EXCEPTION 'A choice with this URL already exists for this attribute';\n                    END IF;\n                    RETURN NEW;\n                ", hash='93cfcc7aac8e6667e448ee57f7c48245ce787fee', operation='INSERT OR UPDATE', pgid='pgtrigger_prevent_duplicate_link_choice_cd780', table='assets_linkattributechoice', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='numberattributechoice',
            trigger=pgtrigger.compiler.Trigger(name='prevent_duplicate_number_choice', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n                    IF EXISTS (\n                        SELECT 1\n                        FROM public.assets_numberattributechoice nc\n                        JOIN public.assets_assettypeattributechoice base ON nc.assettypeattributechoice_ptr_id = base.id\n                        WHERE base.asset_type_attribute_id = (\n                            SELECT asset_type_attribute_id FROM public.assets_assettypeattributechoice WHERE id = NEW.assettypeattributechoice_ptr_id\n                        )\n                        AND nc.value = NEW.value\n                        AND nc.assettypeattributechoice_ptr_id != NEW.assettypeattributechoice_ptr_id\n                        AND base.deleted_at IS NULL\n                    ) THEN\n                        RAISE EXCEPTION 'A choice with this value already exists for this attribute';\n                    END IF;\n                    RETURN NEW;\n                ", hash='c8f30b54b5be05d1af11af9d5fdc0a2d465d6126', operation='INSERT OR UPDATE', pgid='pgtrigger_prevent_duplicate_number_choice_35361', table='assets_numberattributechoice', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='textattributechoice',
            trigger=pgtrigger.compiler.Trigger(name='prevent_duplicate_text_choice', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n                    IF EXISTS (\n                        SELECT 1\n                        FROM public.assets_textattributechoice tc\n                        JOIN public.assets_assettypeattributechoice base ON tc.assettypeattributechoice_ptr_id = base.id\n                        WHERE base.asset_type_attribute_id = (\n                            SELECT asset_type_attribute_id FROM public.assets_assettypeattributechoice WHERE id = NEW.assettypeattributechoice_ptr_id\n                        )\n                        AND tc.value = NEW.value\n                        AND tc.assettypeattributechoice_ptr_id != NEW.assettypeattributechoice_ptr_id\n                        AND base.deleted_at IS NULL\n                    ) THEN\n                        RAISE EXCEPTION 'A choice with this value already exists for this attribute';\n                    END IF;\n                    RETURN NEW;\n                ", hash='c1bab97c4252d4c2d6a37e22a4066bd02e1c85d3', operation='INSERT OR UPDATE', pgid='pgtrigger_prevent_duplicate_text_choice_29995', table='assets_textattributechoice', when='BEFORE')),
        ),
    ]
