# Generated by Django 6.0.1 on 2026-01-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_alter_dateattributechoice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booleanattributevalue',
            name='value',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='dateattributevalue',
            name='value',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='datetimeattributevalue',
            name='value',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='linkattributevalue',
            name='display_text',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='linkattributevalue',
            name='url',
            field=models.URLField(blank=True, db_index=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='numberattributevalue',
            name='value',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='textattributevalue',
            name='value',
            field=models.TextField(blank=True, db_index=True),
        ),
    ]
