# Generated by Django 6.0.1 on 2026-01-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_alter_booleanattributevalue_value_and_more'),
        ('files_manager', '0002_initial'),
        ('organizations', '0003_organization_unique_organization_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['asset_type_id', 'created_at'], name='idx_asset_type_created'),
        ),
    ]
