# Generated by Django 6.0.1 on 2026-01-19 04:21

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("assets", "0016_asset_idx_org_h3_and_more"),
        ("files_manager", "0003_alter_directory_managers"),
        ("organizations", "0003_organization_unique_organization_name"),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_asset_org_h3_prefix_1_created_at_desc "
                "ON assets_asset (organization_id, LEFT(h3_index, 1), created_at DESC);"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS idx_asset_org_h3_prefix_1_created_at_desc;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_asset_org_h3_prefix_2_created_at_desc "
                "ON assets_asset (organization_id, LEFT(h3_index, 2), created_at DESC);"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS idx_asset_org_h3_prefix_2_created_at_desc;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_asset_org_h3_prefix_3_created_at_desc "
                "ON assets_asset (organization_id, LEFT(h3_index, 3), created_at DESC);"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS idx_asset_org_h3_prefix_3_created_at_desc;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_asset_org_h3_prefix_4_created_at_desc "
                "ON assets_asset (organization_id, LEFT(h3_index, 4), created_at DESC);"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS idx_asset_org_h3_prefix_4_created_at_desc;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_asset_org_h3_prefix_5_created_at_desc "
                "ON assets_asset (organization_id, LEFT(h3_index, 5), created_at DESC);"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS idx_asset_org_h3_prefix_5_created_at_desc;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_asset_org_h3_prefix_6_created_at_desc "
                "ON assets_asset (organization_id, LEFT(h3_index, 6), created_at DESC);"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS idx_asset_org_h3_prefix_6_created_at_desc;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_asset_org_h3_prefix_7_created_at_desc "
                "ON assets_asset (organization_id, LEFT(h3_index, 7), created_at DESC);"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS idx_asset_org_h3_prefix_7_created_at_desc;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_asset_org_h3_prefix_8_created_at_desc "
                "ON assets_asset (organization_id, LEFT(h3_index, 8), created_at DESC);"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS idx_asset_org_h3_prefix_8_created_at_desc;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_asset_org_h3_prefix_9_created_at_desc "
                "ON assets_asset (organization_id, LEFT(h3_index, 9), created_at DESC);"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS idx_asset_org_h3_prefix_9_created_at_desc;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_asset_org_h3_prefix_10_created_at_desc "
                "ON assets_asset (organization_id, LEFT(h3_index, 10), created_at DESC);"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS idx_asset_org_h3_prefix_10_created_at_desc;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_asset_org_h3_prefix_11_created_at_desc "
                "ON assets_asset (organization_id, LEFT(h3_index, 11), created_at DESC);"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS idx_asset_org_h3_prefix_11_created_at_desc;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_asset_org_h3_prefix_12_created_at_desc "
                "ON assets_asset (organization_id, LEFT(h3_index, 12), created_at DESC);"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS idx_asset_org_h3_prefix_12_created_at_desc;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_asset_org_h3_prefix_13_created_at_desc "
                "ON assets_asset (organization_id, LEFT(h3_index, 13), created_at DESC);"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS idx_asset_org_h3_prefix_13_created_at_desc;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_asset_org_h3_prefix_14_created_at_desc "
                "ON assets_asset (organization_id, LEFT(h3_index, 14), created_at DESC);"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS idx_asset_org_h3_prefix_14_created_at_desc;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_asset_org_h3_prefix_15_created_at_desc "
                "ON assets_asset (organization_id, LEFT(h3_index, 15), created_at DESC);"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS idx_asset_org_h3_prefix_15_created_at_desc;"
            ),
        ),
        # Ensure btree_gist extension for mixing btree and gist indexes
        migrations.RunSQL(
            sql=("CREATE EXTENSION IF NOT EXISTS btree_gist WITH SCHEMA public;"),
            reverse_sql=migrations.RunSQL.noop,
        ),
        # GiST composite index to allow filtering by organization + spatial query
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_asset_org_geometry_gist "
                "ON assets_asset USING GIST (organization_id, geometry);"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS idx_asset_org_geometry_gist;"
            ),
        ),
        # Indexes to speed workspace -> asset joins
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_workspaceasset_workspace_id_asset_id "
                "ON assets_workspaceasset (workspace_id, asset_id);"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS idx_workspaceasset_workspace_id_asset_id;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_workspaceasset_workspace_id_added_at "
                "ON assets_workspaceasset (workspace_id, added_at DESC);"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS idx_workspaceasset_workspace_id_added_at;"
            ),
        ),
    ]
