# Generated by Django 6.0.1 on 2026-01-19 05:06

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_asset_h3_idx_org_created_at_location'),
        ('files_manager', '0003_alter_directory_managers'),
        ('organizations', '0003_organization_unique_organization_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='asset',
            index=django.contrib.postgres.indexes.GistIndex(fields=['geometry'], name='gist_idx_geometry'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=django.contrib.postgres.indexes.GistIndex(fields=['location'], name='gist_idx_location'),
        ),
    ]
