# Generated by Django 6.0.1 on 2026-01-18

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("assets", "0018_asset_gist_idx_geometry_asset_gist_idx_location"),
    ]

    operations = [
        # Functional indexes on LEFT(h3_index, N) without organization_id
        # These support workspace-scoped queries that filter by h3 prefix
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_asset_h3_prefix_1_created_at_desc "
                "ON assets_asset (LEFT(h3_index, 1), created_at DESC) "
                "WHERE deleted_at IS NULL;"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS idx_asset_h3_prefix_1_created_at_desc;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_asset_h3_prefix_2_created_at_desc "
                "ON assets_asset (LEFT(h3_index, 2), created_at DESC) "
                "WHERE deleted_at IS NULL;"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS idx_asset_h3_prefix_2_created_at_desc;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_asset_h3_prefix_3_created_at_desc "
                "ON assets_asset (LEFT(h3_index, 3), created_at DESC) "
                "WHERE deleted_at IS NULL;"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS idx_asset_h3_prefix_3_created_at_desc;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_asset_h3_prefix_4_created_at_desc "
                "ON assets_asset (LEFT(h3_index, 4), created_at DESC) "
                "WHERE deleted_at IS NULL;"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS idx_asset_h3_prefix_4_created_at_desc;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_asset_h3_prefix_5_created_at_desc "
                "ON assets_asset (LEFT(h3_index, 5), created_at DESC) "
                "WHERE deleted_at IS NULL;"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS idx_asset_h3_prefix_5_created_at_desc;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_asset_h3_prefix_6_created_at_desc "
                "ON assets_asset (LEFT(h3_index, 6), created_at DESC) "
                "WHERE deleted_at IS NULL;"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS idx_asset_h3_prefix_6_created_at_desc;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_asset_h3_prefix_7_created_at_desc "
                "ON assets_asset (LEFT(h3_index, 7), created_at DESC) "
                "WHERE deleted_at IS NULL;"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS idx_asset_h3_prefix_7_created_at_desc;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_asset_h3_prefix_8_created_at_desc "
                "ON assets_asset (LEFT(h3_index, 8), created_at DESC) "
                "WHERE deleted_at IS NULL;"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS idx_asset_h3_prefix_8_created_at_desc;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_asset_h3_prefix_9_created_at_desc "
                "ON assets_asset (LEFT(h3_index, 9), created_at DESC) "
                "WHERE deleted_at IS NULL;"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS idx_asset_h3_prefix_9_created_at_desc;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_asset_h3_prefix_10_created_at_desc "
                "ON assets_asset (LEFT(h3_index, 10), created_at DESC) "
                "WHERE deleted_at IS NULL;"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS idx_asset_h3_prefix_10_created_at_desc;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_asset_h3_prefix_11_created_at_desc "
                "ON assets_asset (LEFT(h3_index, 11), created_at DESC) "
                "WHERE deleted_at IS NULL;"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS idx_asset_h3_prefix_11_created_at_desc;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_asset_h3_prefix_12_created_at_desc "
                "ON assets_asset (LEFT(h3_index, 12), created_at DESC) "
                "WHERE deleted_at IS NULL;"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS idx_asset_h3_prefix_12_created_at_desc;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_asset_h3_prefix_13_created_at_desc "
                "ON assets_asset (LEFT(h3_index, 13), created_at DESC) "
                "WHERE deleted_at IS NULL;"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS idx_asset_h3_prefix_13_created_at_desc;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_asset_h3_prefix_14_created_at_desc "
                "ON assets_asset (LEFT(h3_index, 14), created_at DESC) "
                "WHERE deleted_at IS NULL;"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS idx_asset_h3_prefix_14_created_at_desc;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_asset_h3_prefix_15_created_at_desc "
                "ON assets_asset (LEFT(h3_index, 15), created_at DESC) "
                "WHERE deleted_at IS NULL;"
            ),
            reverse_sql=(
                "DROP INDEX CONCURRENTLY IF EXISTS idx_asset_h3_prefix_15_created_at_desc;"
            ),
        ),
    ]
