# Generated by Django 6.0.1 on 2026-01-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0019_asset_h3_prefix_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='max_render_zoom',
            field=models.PositiveSmallIntegerField(default=22, help_text='Maximum zoom level at which assets of this type are visible (0-22)'),
        ),
        migrations.AddField(
            model_name='assettype',
            name='min_render_zoom',
            field=models.PositiveSmallIntegerField(default=0, help_text='Minimum zoom level at which assets of this type are visible (0-22)'),
        ),
    ]
