# Generated by Django 6.0.1 on 2026-01-14 14:50

import django.db.models.deletion
import django.db.models.manager
import files_manager.models.file_node
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileNode',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='File or folder name', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('filenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files_manager.filenode')),
                ('file', models.FileField(help_text='The actual file', upload_to=files_manager.models.file_node.file_upload_path)),
                ('size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('mime_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=255, null=True)),
                ('duration', models.DurationField(blank=True, help_text='Audio duration', null=True)),
                ('artist', models.CharField(blank=True, help_text='Artist/performer', max_length=255)),
                ('album', models.CharField(blank=True, help_text='Album name', max_length=255)),
                ('track_number', models.PositiveIntegerField(blank=True, help_text='Track number', null=True)),
                ('codec', models.CharField(blank=True, help_text='Audio codec (e.g., mp3, aac, flac)', max_length=50)),
                ('bitrate', models.PositiveIntegerField(blank=True, help_text='Bitrate in kbps', null=True)),
                ('sample_rate', models.PositiveIntegerField(blank=True, help_text='Sample rate in Hz', null=True)),
            ],
            options={
                'verbose_name': 'Audio',
                'verbose_name_plural': 'Audio Files',
            },
            bases=('files_manager.filenode',),
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('filenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files_manager.filenode')),
                ('description', models.TextField(blank=True, help_text='Optional description of the folder')),
                ('color', models.CharField(blank=True, help_text='Hex color for folder icon (e.g., #FF5733)', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Icon identifier for the folder', max_length=50)),
            ],
            options={
                'verbose_name': 'Directory',
                'verbose_name_plural': 'Directories',
            },
            bases=('files_manager.filenode',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('filenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files_manager.filenode')),
                ('file', models.FileField(help_text='The actual file', upload_to=files_manager.models.file_node.file_upload_path)),
                ('size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('mime_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=255, null=True)),
                ('page_count', models.PositiveIntegerField(blank=True, help_text='Number of pages (for PDFs, docs)', null=True)),
                ('text_content', models.TextField(blank=True, help_text='Extracted text content for search')),
                ('author', models.CharField(blank=True, help_text='Document author', max_length=255)),
                ('title', models.CharField(blank=True, help_text='Document title from metadata', max_length=500)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
            bases=('files_manager.filenode',),
        ),
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('filenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files_manager.filenode')),
                ('file', models.FileField(help_text='The actual file', upload_to=files_manager.models.file_node.file_upload_path)),
                ('size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('mime_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=255, null=True)),
                ('width', models.PositiveIntegerField(blank=True, help_text='Image width in pixels', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Image height in pixels', null=True)),
                ('thumbnail_url', models.URLField(blank=True, help_text='URL to thumbnail image', max_length=500, null=True)),
                ('exif_data', models.JSONField(blank=True, help_text='Extracted EXIF metadata', null=True)),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=500)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
            bases=('files_manager.filenode',),
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('filenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files_manager.filenode')),
                ('file', models.FileField(help_text='The actual file', upload_to=files_manager.models.file_node.file_upload_path)),
                ('size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('mime_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=255, null=True)),
                ('duration', models.DurationField(blank=True, help_text='Video duration', null=True)),
                ('width', models.PositiveIntegerField(blank=True, help_text='Video width in pixels', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Video height in pixels', null=True)),
                ('thumbnail_url', models.URLField(blank=True, help_text='URL to video thumbnail', max_length=500, null=True)),
                ('codec', models.CharField(blank=True, help_text='Video codec (e.g., h264, vp9)', max_length=50)),
                ('frame_rate', models.FloatField(blank=True, help_text='Frames per second', null=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
            bases=('files_manager.filenode',),
        ),
    ]
