# Generated by Django 6.0.1 on 2026-01-14 14:50

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files_manager', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filenode',
            name='workspace',
            field=models.ForeignKey(help_text='Workspace this file/folder belongs to (for access control)', on_delete=django.db.models.deletion.CASCADE, related_name='file_nodes', to='workspaces.workspace'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='audiofile',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE files_manager_filenode\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.filenode_ptr_id;\n                        RETURN NULL;\n                        ', hash='bbaebe788a06564b3e7702cd9d01e2e71ab99e72', operation='DELETE', pgid='pgtrigger_soft_delete_7ba15', table='files_manager_audiofile', when='BEFORE')),
        ),
        migrations.AddField(
            model_name='filenode',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent directory (null only for root directory)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='files_manager.directory'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='directory',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE files_manager_filenode\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.filenode_ptr_id;\n                        RETURN NULL;\n                        ', hash='7998bc91cae946f078310ea9c9d62baf5b406e4b', operation='DELETE', pgid='pgtrigger_soft_delete_0972a', table='files_manager_directory', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='documentfile',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE files_manager_filenode\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.filenode_ptr_id;\n                        RETURN NULL;\n                        ', hash='6d079e2df4f4f04374f0679cd5285bfa044f8875', operation='DELETE', pgid='pgtrigger_soft_delete_6bb39', table='files_manager_documentfile', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='imagefile',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE files_manager_filenode\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.filenode_ptr_id;\n                        RETURN NULL;\n                        ', hash='bdfd5c09309912d84238a6b301d1cc5863af3f2c', operation='DELETE', pgid='pgtrigger_soft_delete_47657', table='files_manager_imagefile', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='videofile',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE files_manager_filenode\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.filenode_ptr_id;\n                        RETURN NULL;\n                        ', hash='650abba1a2c9325fc292b83d0877efe366de90a5', operation='DELETE', pgid='pgtrigger_soft_delete_fa7e8', table='files_manager_videofile', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='filenode',
            index=models.Index(fields=['workspace', 'parent'], name='files_manag_workspa_10482a_idx'),
        ),
        migrations.AddConstraint(
            model_name='filenode',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'parent', 'name'), name='unique_name_in_folder'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='filenode',
            trigger=pgtrigger.compiler.Trigger(name='001_unique_root_directory', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n                    -- Only check for Directory types (check polymorphic_ctype)\n                    -- Get the content type ID for Directory model\n                    DECLARE\n                        directory_ctype_id INTEGER;\n                        existing_root_count INTEGER;\n                    BEGIN\n                        -- Get Directory content type ID\n                        SELECT id INTO directory_ctype_id\n                        FROM django_content_type\n                        WHERE app_label = 'files_manager' AND model = 'directory';\n                        \n                        -- Only enforce for Directory types with no parent (root)\n                        IF NEW.polymorphic_ctype_id = directory_ctype_id \n                           AND NEW.parent_id IS NULL \n                           AND NEW.deleted_at IS NULL THEN\n                            \n                            -- Check if another root exists for this workspace\n                            SELECT COUNT(*) INTO existing_root_count\n                            FROM files_manager_filenode\n                            WHERE workspace_id = NEW.workspace_id\n                              AND parent_id IS NULL\n                              AND deleted_at IS NULL\n                              AND polymorphic_ctype_id = directory_ctype_id\n                              AND id != NEW.id;\n                            \n                            IF existing_root_count > 0 THEN\n                                RAISE EXCEPTION 'Only one root directory allowed per workspace';\n                            END IF;\n                        END IF;\n                        \n                        RETURN NEW;\n                    END;\n                    ", hash='f34c34d8b2c1a437c4b4cf0b4bf8b53fa38418b5', operation='INSERT OR UPDATE', pgid='pgtrigger_001_unique_root_directory_a11dc', table='files_manager_filenode', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='filenode',
            trigger=pgtrigger.compiler.Trigger(name='002_files_require_parent', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n                    DECLARE\n                        directory_ctype_id INTEGER;\n                    BEGIN\n                        -- Get Directory content type ID\n                        SELECT id INTO directory_ctype_id\n                        FROM django_content_type\n                        WHERE app_label = 'files_manager' AND model = 'directory';\n                        \n                        -- If not a Directory and parent is null, reject\n                        IF NEW.polymorphic_ctype_id != directory_ctype_id \n                           AND NEW.parent_id IS NULL \n                           AND NEW.deleted_at IS NULL THEN\n                            RAISE EXCEPTION 'Files must have a parent directory';\n                        END IF;\n                        \n                        RETURN NEW;\n                    END;\n                    ", hash='7267ea1e8f4b89d47f9b591db7ae974fd6349bfc', operation='INSERT OR UPDATE', pgid='pgtrigger_002_files_require_parent_c2e94', table='files_manager_filenode', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='filenode',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            UPDATE files_manager_filenode \n            SET deleted_at = NOW()\n            WHERE id = OLD.id;\n            RETURN NULL;\n            ', hash='521c418245b6e8ac0fb020d9bf69c516751ed69a', operation='DELETE', pgid='pgtrigger_soft_delete_38b56', table='files_manager_filenode', when='BEFORE')),
        ),
    ]
