# Generated by Django 6.0.1 on 2026-01-18 19:04

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files_manager', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='directory',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
