# Generated by Django 6.0.1 on 2026-01-12 04:51

import django.db.models.deletion
import django.db.models.manager
import files.models.file_node
import pgtrigger.compiler
import pgtrigger.migrations
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileNode',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='File or folder name', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('workspace', models.ForeignKey(help_text='Workspace this file/folder belongs to (for access control)', on_delete=django.db.models.deletion.CASCADE, related_name='file_nodes', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('filenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.filenode')),
                ('file', models.FileField(help_text='The actual file', upload_to=files.models.file_node.file_upload_path)),
                ('size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('mime_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=255, null=True)),
                ('duration', models.DurationField(blank=True, help_text='Audio duration', null=True)),
                ('artist', models.CharField(blank=True, help_text='Artist/performer', max_length=255)),
                ('album', models.CharField(blank=True, help_text='Album name', max_length=255)),
                ('track_number', models.PositiveIntegerField(blank=True, help_text='Track number', null=True)),
                ('codec', models.CharField(blank=True, help_text='Audio codec (e.g., mp3, aac, flac)', max_length=50)),
                ('bitrate', models.PositiveIntegerField(blank=True, help_text='Bitrate in kbps', null=True)),
                ('sample_rate', models.PositiveIntegerField(blank=True, help_text='Sample rate in Hz', null=True)),
            ],
            options={
                'verbose_name': 'Audio',
                'verbose_name_plural': 'Audio Files',
            },
            bases=('files.filenode',),
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('filenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.filenode')),
                ('description', models.TextField(blank=True, help_text='Optional description of the folder')),
                ('color', models.CharField(blank=True, help_text='Hex color for folder icon (e.g., #FF5733)', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Icon identifier for the folder', max_length=50)),
            ],
            options={
                'verbose_name': 'Directory',
                'verbose_name_plural': 'Directories',
            },
            bases=('files.filenode',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('filenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.filenode')),
                ('file', models.FileField(help_text='The actual file', upload_to=files.models.file_node.file_upload_path)),
                ('size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('mime_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=255, null=True)),
                ('page_count', models.PositiveIntegerField(blank=True, help_text='Number of pages (for PDFs, docs)', null=True)),
                ('text_content', models.TextField(blank=True, help_text='Extracted text content for search')),
                ('author', models.CharField(blank=True, help_text='Document author', max_length=255)),
                ('title', models.CharField(blank=True, help_text='Document title from metadata', max_length=500)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
            bases=('files.filenode',),
        ),
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('filenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.filenode')),
                ('file', models.FileField(help_text='The actual file', upload_to=files.models.file_node.file_upload_path)),
                ('size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('mime_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=255, null=True)),
                ('width', models.PositiveIntegerField(blank=True, help_text='Image width in pixels', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Image height in pixels', null=True)),
                ('thumbnail_url', models.URLField(blank=True, help_text='URL to thumbnail image', max_length=500, null=True)),
                ('exif_data', models.JSONField(blank=True, help_text='Extracted EXIF metadata', null=True)),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=500)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
            bases=('files.filenode',),
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('filenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.filenode')),
                ('file', models.FileField(help_text='The actual file', upload_to=files.models.file_node.file_upload_path)),
                ('size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('mime_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=255, null=True)),
                ('duration', models.DurationField(blank=True, help_text='Video duration', null=True)),
                ('width', models.PositiveIntegerField(blank=True, help_text='Video width in pixels', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Video height in pixels', null=True)),
                ('thumbnail_url', models.URLField(blank=True, help_text='URL to video thumbnail', max_length=500, null=True)),
                ('codec', models.CharField(blank=True, help_text='Video codec (e.g., h264, vp9)', max_length=50)),
                ('frame_rate', models.FloatField(blank=True, help_text='Frames per second', null=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
            bases=('files.filenode',),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='audiofile',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE files_filenode\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.filenode_ptr_id;\n                        RETURN NULL;\n                        ', hash='abedde446c5c5871433272fa4e8edcd25f5c7eae', operation='DELETE', pgid='pgtrigger_soft_delete_69484', table='files_audiofile', when='BEFORE')),
        ),
        migrations.AddField(
            model_name='filenode',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent directory (null only for root directory)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='files.directory'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='directory',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE files_filenode\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.filenode_ptr_id;\n                        RETURN NULL;\n                        ', hash='73c75dc180574c2f8cdbb3a210114faa636447d1', operation='DELETE', pgid='pgtrigger_soft_delete_eb538', table='files_directory', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='documentfile',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE files_filenode\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.filenode_ptr_id;\n                        RETURN NULL;\n                        ', hash='13066cebf19fdd2095808718b15b48a350906c94', operation='DELETE', pgid='pgtrigger_soft_delete_ee09d', table='files_documentfile', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='imagefile',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE files_filenode\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.filenode_ptr_id;\n                        RETURN NULL;\n                        ', hash='b12407d60f017163835f0e0f096319b07e259b04', operation='DELETE', pgid='pgtrigger_soft_delete_9ab98', table='files_imagefile', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='videofile',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                        UPDATE files_filenode\n                        SET deleted_at = NOW()\n                        WHERE id = OLD.filenode_ptr_id;\n                        RETURN NULL;\n                        ', hash='1297219bdff15d3fe11220292cb219194b910927', operation='DELETE', pgid='pgtrigger_soft_delete_1e463', table='files_videofile', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='filenode',
            index=models.Index(fields=['workspace', 'parent'], name='files_filen_workspa_44bfe3_idx'),
        ),
        migrations.AddConstraint(
            model_name='filenode',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'parent', 'name'), name='unique_name_in_folder'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='filenode',
            trigger=pgtrigger.compiler.Trigger(name='001_unique_root_directory', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n                    -- Only check for Directory types (check polymorphic_ctype)\n                    -- Get the content type ID for Directory model\n                    DECLARE\n                        directory_ctype_id INTEGER;\n                        existing_root_count INTEGER;\n                    BEGIN\n                        -- Get Directory content type ID\n                        SELECT id INTO directory_ctype_id\n                        FROM django_content_type\n                        WHERE app_label = 'files' AND model = 'directory';\n                        \n                        -- Only enforce for Directory types with no parent (root)\n                        IF NEW.polymorphic_ctype_id = directory_ctype_id \n                           AND NEW.parent_id IS NULL \n                           AND NEW.deleted_at IS NULL THEN\n                            \n                            -- Check if another root exists for this workspace\n                            SELECT COUNT(*) INTO existing_root_count\n                            FROM files_filenode\n                            WHERE workspace_id = NEW.workspace_id\n                              AND parent_id IS NULL\n                              AND deleted_at IS NULL\n                              AND polymorphic_ctype_id = directory_ctype_id\n                              AND id != NEW.id;\n                            \n                            IF existing_root_count > 0 THEN\n                                RAISE EXCEPTION 'Only one root directory allowed per workspace';\n                            END IF;\n                        END IF;\n                        \n                        RETURN NEW;\n                    END;\n                    ", hash='4d1c0c19a3df867a1b75e0b981df86d94bf06965', operation='INSERT OR UPDATE', pgid='pgtrigger_001_unique_root_directory_08764', table='files_filenode', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='filenode',
            trigger=pgtrigger.compiler.Trigger(name='002_files_require_parent', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n                    DECLARE\n                        directory_ctype_id INTEGER;\n                    BEGIN\n                        -- Get Directory content type ID\n                        SELECT id INTO directory_ctype_id\n                        FROM django_content_type\n                        WHERE app_label = 'files' AND model = 'directory';\n                        \n                        -- If not a Directory and parent is null, reject\n                        IF NEW.polymorphic_ctype_id != directory_ctype_id \n                           AND NEW.parent_id IS NULL \n                           AND NEW.deleted_at IS NULL THEN\n                            RAISE EXCEPTION 'Files must have a parent directory';\n                        END IF;\n                        \n                        RETURN NEW;\n                    END;\n                    ", hash='76d55c92c87aa648f9c8f5eabe4ad44b27d5954d', operation='INSERT OR UPDATE', pgid='pgtrigger_002_files_require_parent_055c1', table='files_filenode', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='filenode',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            UPDATE files_filenode \n            SET deleted_at = NOW()\n            WHERE id = OLD.id;\n            RETURN NULL;\n            ', hash='76cc0695710912afb418113ee4ed7d21db535b9a', operation='DELETE', pgid='pgtrigger_soft_delete_cf8ac', table='files_filenode', when='BEFORE')),
        ),
    ]
