# Generated by Django 6.0.1 on 2026-01-19 17:35

import django.db.models.deletion
import django.db.models.manager
import pgtrigger.compiler
import pgtrigger.migrations
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_organization_unique_organization_name'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('theme_preset', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('blue', 'Blue'), ('high-contrast', 'High Contrast'), ('custom', 'Custom')], default='light', max_length=20)),
                ('theme_customizations', models.JSONField(blank=True, default=dict, help_text='Custom theme color overrides')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_org_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Settings',
                'verbose_name_plural': 'Organization Settings',
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceSettings',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('theme_preset', models.CharField(blank=True, choices=[('light', 'Light'), ('dark', 'Dark'), ('blue', 'Blue'), ('high-contrast', 'High Contrast'), ('custom', 'Custom')], help_text='Leave blank to inherit from organization', max_length=20, null=True)),
                ('theme_customizations', models.JSONField(blank=True, default=dict, help_text='Custom theme color overrides (merged with org settings)')),
                ('inherit_theme', models.BooleanField(default=True, help_text='If true, inherit theme from organization settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_ws_settings', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Workspace Settings',
                'verbose_name_plural': 'Workspace Settings',
                'abstract': False,
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='organizationsettings',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            UPDATE settings_organizationsettings \n            SET deleted_at = NOW()\n            WHERE id = OLD.id;\n            RETURN NULL;\n            ', hash='f11c0eaeda9288e26f93d12967267663a65ee18a', operation='DELETE', pgid='pgtrigger_soft_delete_2c889', table='settings_organizationsettings', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='workspacesettings',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            UPDATE settings_workspacesettings \n            SET deleted_at = NOW()\n            WHERE id = OLD.id;\n            RETURN NULL;\n            ', hash='c26379f0467e42662a4d61d15fd70e6837b43dc5', operation='DELETE', pgid='pgtrigger_soft_delete_2c1ec', table='settings_workspacesettings', when='BEFORE')),
        ),
    ]
