# Generated by Django 6.0.1 on 2026-01-19 18:53

import django.db.models.manager
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_rename_savedtheme_to_theme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'default_manager_name': 'all_objects', 'ordering': ['theme_type', 'name'], 'verbose_name': 'Theme', 'verbose_name_plural': 'Themes'},
        ),
        migrations.AlterModelManagers(
            name='theme',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='theme',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='theme',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='light_customizations',
            field=models.JSONField(default=dict, help_text='Light mode theme color customizations'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='theme',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            UPDATE settings_theme \n            SET deleted_at = NOW()\n            WHERE id = OLD.id;\n            RETURN NULL;\n            ', hash='3e71f5bf9a68328c401d2be73ac6b53168336f23', operation='DELETE', pgid='pgtrigger_soft_delete_084e0', table='settings_theme', when='BEFORE')),
        ),
    ]
