# Generated by Django 6.0.1 on 2026-01-14 19:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organizations', '0002_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogPendingBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(help_text='Serialized batch data for processing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['processed', 'created_at'], name='audit_log_a_process_df9568_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLogRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.CharField(blank=True, db_index=True, help_text='Unique request identifier for correlation (e.g., X-Request-ID header)', max_length=100)),
                ('user_email', models.EmailField(blank=True, help_text='Stored separately in case user is deleted', max_length=254)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('request_query_params', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Request duration in milliseconds', null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_requests', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_requests', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_requests', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_id', models.UUIDField(blank=True, db_index=True, help_text='Optional group ID for custom batching within a request', null=True)),
                ('action', models.CharField(choices=[('create', 'Created'), ('read', 'Read'), ('update', 'Updated'), ('delete', 'Deleted'), ('destroy', 'Destroyed'), ('list', 'Listed'), ('retrieve', 'Retrieved'), ('export', 'Exported'), ('import', 'Imported'), ('login', 'Logged In'), ('logout', 'Logged Out'), ('permission', 'Permission Changed'), ('custom', 'Custom Action')], db_index=True, max_length=50)),
                ('action_detail', models.CharField(blank=True, help_text="More specific action, e.g., 'workspace_local', 'global'", max_length=100)),
                ('message', models.TextField(help_text="Human-readable description like 'Updated attribute X on Asset Y'")),
                ('target_object_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('target_repr', models.CharField(blank=True, help_text='String representation of target at time of action', max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Dict of field changes: {field: {old: x, new: y}}')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('order', models.IntegerField(default=0, help_text='Order within the batch')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries_as_target', to='contenttypes.contenttype')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='audit_log.auditlogrequest')),
            ],
            options={
                'ordering': ['-created_at', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AuditLogReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(db_index=True, max_length=100)),
                ('object_repr', models.CharField(blank=True, help_text='String representation at time of action', max_length=255)),
                ('role', models.CharField(default='affected', help_text="Role: 'target', 'parent', 'workspace', 'organization', etc.", max_length=50)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='audit_log.auditlogentry')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='audit_log_a_content_9486a9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='auditlogrequest',
            index=models.Index(fields=['user', '-created_at'], name='audit_log_a_user_id_c0c7f2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogrequest',
            index=models.Index(fields=['organization', '-created_at'], name='audit_log_a_organiz_ee9c52_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogrequest',
            index=models.Index(fields=['workspace', '-created_at'], name='audit_log_a_workspa_51d2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogrequest',
            index=models.Index(fields=['request_id'], name='audit_log_a_request_1acbd1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['request', 'order'], name='audit_log_a_request_521996_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['group_id'], name='audit_log_a_group_i_9b294b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['action', '-created_at'], name='audit_log_a_action_967a23_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['target_content_type', 'target_object_id'], name='audit_log_a_target__94d2dd_idx'),
        ),
    ]
