# Generated by Django 6.0.1 on 2026-01-14 20:18

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='Description of what this group of actions represents', max_length=255)),
                ('source_type', models.CharField(blank=True, help_text="Type of source that created this group (e.g., 'management_command', 'celery_task')", max_length=100)),
                ('source_name', models.CharField(blank=True, help_text="Name of the source (e.g., 'startorganization', 'import_assets')", max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the group')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='auditlogentry',
            name='group_id',
        ),
        migrations.AddField(
            model_name='auditlogrequest',
            name='source',
            field=models.CharField(choices=[('api', 'API Request'), ('management_command', 'Management Command'), ('celery_task', 'Celery Task'), ('system', 'System'), ('migration', 'Migration')], db_index=True, default='api', help_text='Origin of the action (api, management_command, celery_task, system)', max_length=50),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='auditlogentry',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='f01ba52f9f38c28500df8f3c57812f1f9405ceee', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_2830e', table='audit_log_auditlogentry', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='auditlogreference',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='aac02a00dd874a90cee1357d23fd3ef4907df86b', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_90f1c', table='audit_log_auditlogreference', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='auditlogrequest',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='6033aaaf367dd9e9fc56ef060620e2b2c5bbea13', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_e2a47', table='audit_log_auditlogrequest', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='auditloggroup',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='aa2f73bd62d7e74e27861e0ad38a35544f65456c', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_94cce', table='audit_log_auditloggroup', when='BEFORE')),
        ),
        migrations.AddField(
            model_name='auditlogentry',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Optional group for linking related entries with a description', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='audit_log.auditloggroup'),
        ),
    ]
