# Generated by Django 6.0.1 on 2026-01-14 14:50

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'user'), name='unique_organization_user'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='organizationmembership',
            trigger=pgtrigger.compiler.Trigger(name='soft_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            UPDATE organizations_organizationmembership \n            SET deleted_at = NOW()\n            WHERE id = OLD.id;\n            RETURN NULL;\n            ', hash='406b3bba472a14355a8f5aec43aec78f7f575da9', operation='DELETE', pgid='pgtrigger_soft_delete_eedff', table='organizations_organizationmembership', when='BEFORE')),
        ),
    ]
